-- cdk_accounting_schedule (accounting-schedule) -- Accounting Schedule (Open-Item Subledger)
-- Schedule
-- SAP analogue: Reconciliation account open-item subledger (FBL3N / open items behind SKB1-XMITKZ accounts)
-- grain: one row per open item per schedule per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_accounting_schedule (
    schedule_id VARCHAR(32),
    gl_account_number VARCHAR(10) NOT NULL,
    control_key_type VARCHAR(32) NOT NULL,
    control_key_value VARCHAR(32) NOT NULL,
    open_item_amount NUMBER(13,2) NOT NULL,
    aging_bucket VARCHAR(32),
    posting_date DATE NOT NULL,
    schedule_type VARCHAR(32) NOT NULL,
    schedule_index_legacy VARCHAR(32),
    is_closed BOOLEAN,
    _rooftop_id VARCHAR(20),
    _extracted_at TIMESTAMP_NTZ,
    _source_route VARCHAR(16),
    _batch_id VARCHAR(64),
    PRIMARY KEY (schedule_id)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on schedule_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_accounting_schedule.schedule_id IS '[I] Schedule ID';
COMMENT ON COLUMN cdk_accounting_schedule.gl_account_number IS '[D] Controlling GL Account';
COMMENT ON COLUMN cdk_accounting_schedule.control_key_type IS '[D] Control Key Type (values: RO_NUMBER=Repair order number; CLAIM_NUMBER=Warranty claim number; STOCK_NUMBER=Vehicle stock number; VIN_LAST8=Last 8 characters of VIN; CUSTOMER_ID=Customer ID; DEAL_CONTRACT_NUMBER=Deal/contract reference number; REFERENCE_DOC_NUMBER=General reference/document number)';
COMMENT ON COLUMN cdk_accounting_schedule.control_key_value IS '[D] Control Key Value';
COMMENT ON COLUMN cdk_accounting_schedule.open_item_amount IS '[D] Open Item Amount';
COMMENT ON COLUMN cdk_accounting_schedule.aging_bucket IS '[D] Aging Bucket (values: CURRENT=0-29 days; 30=30-59 days; 60=60-89 days; 90=90-119 days; 120_PLUS=120+ days)';
COMMENT ON COLUMN cdk_accounting_schedule.posting_date IS '[D] Posting Date';
COMMENT ON COLUMN cdk_accounting_schedule.schedule_type IS '[D] Schedule Type (values: WARRANTY_CLAIMS_RECEIVABLE=Warranty claims receivable (GL 263); NEW_VEHICLE_FLOOR_PLAN=New vehicle floor plan (GL 231 asset / 310 liability); FACTORY_RECEIVABLES=Factory receivables (GL 261); CONTRACTS_IN_TRANSIT=Contracts in transit (GL 205); SERVICE_PARTS_WIP=Service/parts work-in-process (GL 247))';
COMMENT ON COLUMN cdk_accounting_schedule.schedule_index_legacy IS '[U] Legacy Schedule Index (cross-DMS) (values: 0=No Schedule; 1=Vehicle Inventory; 2=Accounts Receivable; 3=Accounts Payable; 4=Misc Balance Forward; 5=Misc Detail Forward; 6=Combination)';
COMMENT ON COLUMN cdk_accounting_schedule.is_closed IS '[I] Item Closed/Cleared Flag';
COMMENT ON COLUMN cdk_accounting_schedule._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_accounting_schedule._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_accounting_schedule._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_accounting_schedule._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_accounting_schedule ADD CONSTRAINT fk_cdk_accounting_schedule_gl_account_number FOREIGN KEY (gl_account_number) REFERENCES cdk_gl_account_master (gl_account_number) NOT ENFORCED;
