-- cdk_employee_master (employee-master) -- Employee / Technician Identifiers
-- the tech or advisor record
-- SAP analogue: HR-adjacent Z-fields on transaction tables (no clean HR analogue)
-- grain: one row per employee per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_employee_master (
    employee_id VARCHAR(12) NOT NULL,
    amount NUMBER(13,2),
    created_date DATE,
    status_code VARCHAR(2),
    _rooftop_id VARCHAR(20),
    _extracted_at TIMESTAMP_NTZ,
    _source_route VARCHAR(16),
    _batch_id VARCHAR(64),
    PRIMARY KEY (employee_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_employee_master.employee_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_employee_master.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_employee_master.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_employee_master.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_employee_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_employee_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_employee_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_employee_master._batch_id IS '[D] the extract run/batch identifier this row landed with';
