-- cdk_gl_account_master (gl-account-master) -- GL Account Master
-- Chart of Accounts
-- SAP analogue: SKA1 (G/L Account Master, Chart of Accounts) / SKB1 (Company Code Data)
-- grain: one row per GL account number (+ department suffix) per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_gl_account_master (
    gl_account_number VARCHAR(6) NOT NULL,
    department_suffix VARCHAR(2),
    sub_account_letter VARCHAR(1),
    account_name VARCHAR(60),
    account_type VARCHAR(32),
    normal_balance VARCHAR(32),
    is_control_account BOOLEAN,
    is_department_bound BOOLEAN,
    is_active BOOLEAN,
    _rooftop_id VARCHAR(20),
    _extracted_at TIMESTAMP_NTZ,
    _source_route VARCHAR(16),
    _batch_id VARCHAR(64),
    PRIMARY KEY (gl_account_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_gl_account_master.gl_account_number IS '[D] GL Account Number (base)';
COMMENT ON COLUMN cdk_gl_account_master.department_suffix IS '[D] Department Suffix';
COMMENT ON COLUMN cdk_gl_account_master.sub_account_letter IS '[D] Sub-Account Letter Suffix';
COMMENT ON COLUMN cdk_gl_account_master.account_name IS '[D] Account Name / Description [WIDENED per WIDENING-POLICY.md: SAP SKAT-TXT50 is CHAR(50); DDL emits source-native 60]';
COMMENT ON COLUMN cdk_gl_account_master.account_type IS '[D] Account Type (values: ASSET=200-series: Assets; LIAB_EQUITY=300-series: Liabilities/Equity; SALES=400-series: Sales; COGS=600-series: Cost of Goods Sold; LEASE_RENTAL_COST=700-series: Lease/Rental Cost; OTHER_INCOME_FI=800/900-series: Other Income/F&I)';
COMMENT ON COLUMN cdk_gl_account_master.normal_balance IS '[I] Normal Balance Side (values: DEBIT=Normal debit balance (assets, COGS, lease/rental cost); CREDIT=Normal credit balance (liabilities, equity, sales, other income))';
COMMENT ON COLUMN cdk_gl_account_master.is_control_account IS '[D] Reconciliation/Control Account Flag';
COMMENT ON COLUMN cdk_gl_account_master.is_department_bound IS '[I] Department-Bound Flag';
COMMENT ON COLUMN cdk_gl_account_master.is_active IS '[U] Active Flag';
COMMENT ON COLUMN cdk_gl_account_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_gl_account_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_gl_account_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_gl_account_master._batch_id IS '[D] the extract run/batch identifier this row landed with';
