-- cdk_parts_pick_ticket (parts-pick-ticket) -- Parts Pick Ticket
-- Parts Pick Ticket
-- SAP analogue: Transfer Order / Reservation withdrawal document (LB03/MB1B analogue)
-- grain: one row per pick-ticket line
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_parts_pick_ticket (
    pick_ticket_id VARCHAR(20) NOT NULL,
    ro_number VARCHAR(20),
    counter_sale_id VARCHAR(20),
    part_number VARCHAR(20),
    quantity_picked NUMBER(13,3),
    pick_bin_location VARCHAR(10),
    picked_by_employee_id VARCHAR(10),
    pick_date DATE,
    pick_status VARCHAR(32),
    _rooftop_id VARCHAR(20),
    _extracted_at TIMESTAMP_NTZ,
    _source_route VARCHAR(16),
    _batch_id VARCHAR(64),
    PRIMARY KEY (pick_ticket_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_parts_pick_ticket.pick_ticket_id IS '[D] Pick Ticket ID';
COMMENT ON COLUMN cdk_parts_pick_ticket.ro_number IS '[I] Associated RO Number';
COMMENT ON COLUMN cdk_parts_pick_ticket.counter_sale_id IS '[I] Associated Counter Sale ID';
COMMENT ON COLUMN cdk_parts_pick_ticket.part_number IS '[I] Part Number';
COMMENT ON COLUMN cdk_parts_pick_ticket.quantity_picked IS '[I] Quantity Picked';
COMMENT ON COLUMN cdk_parts_pick_ticket.pick_bin_location IS '[I] Pick Bin Location';
COMMENT ON COLUMN cdk_parts_pick_ticket.picked_by_employee_id IS '[I] Picked-By Employee ID';
COMMENT ON COLUMN cdk_parts_pick_ticket.pick_date IS '[I] Pick Date';
COMMENT ON COLUMN cdk_parts_pick_ticket.pick_status IS '[I] Pick Status (values: OPEN=Not yet picked; PICKED=Picked, awaiting issue; ISSUED=Issued to RO/counter sale)';
COMMENT ON COLUMN cdk_parts_pick_ticket._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_parts_pick_ticket._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_parts_pick_ticket._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_parts_pick_ticket._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_parts_pick_ticket ADD CONSTRAINT fk_cdk_parts_pick_ticket_ro_number FOREIGN KEY (ro_number) REFERENCES cdk_repair_order (ro_number) NOT ENFORCED;
ALTER TABLE cdk_parts_pick_ticket ADD CONSTRAINT fk_cdk_parts_pick_ticket_counter_sale_id FOREIGN KEY (counter_sale_id) REFERENCES cdk_counter_parts_sale (counter_sale_id) NOT ENFORCED;
ALTER TABLE cdk_parts_pick_ticket ADD CONSTRAINT fk_cdk_parts_pick_ticket_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number) NOT ENFORCED;
ALTER TABLE cdk_parts_pick_ticket ADD CONSTRAINT fk_cdk_parts_pick_ticket_picked_by_employee_id FOREIGN KEY (picked_by_employee_id) REFERENCES cdk_employee_master (service_advisor_number) NOT ENFORCED;
