-- cdk_purchase_receipt_document (purchase-receipt-document) -- Purchase / Receipt Document
-- Purchase Order & Receipt
-- SAP analogue: EKKO/EKPO (Purchase Order Header/Item) + MSEG (Material Document, Movement Type 101 Goods Receipt)
-- grain: one row per PO line receipt
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_purchase_receipt_document (
    purchase_order_number VARCHAR(20),
    vendor_id VARCHAR(20),
    po_date DATE,
    po_line_number NUMBER(38,0),
    part_number VARCHAR(20),
    quantity_ordered NUMBER(13,3),
    quantity_received NUMBER(13,3),
    receipt_document_number VARCHAR(20),
    receipt_date DATE,
    asn_number VARCHAR(30),
    invoice_number VARCHAR(20),
    unit_cost NUMBER(13,2),
    three_way_match_status VARCHAR(32),
    ap_posting_gl_account VARCHAR(10),
    movement_type_sap_analogue VARCHAR(4),
    _rooftop_id VARCHAR(20),
    _extracted_at TIMESTAMP_NTZ,
    _source_route VARCHAR(16),
    _batch_id VARCHAR(64),
    PRIMARY KEY (purchase_order_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on purchase_order_number: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)
    -- NOT NULL withheld on vendor_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on po_line_number: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_purchase_receipt_document.purchase_order_number IS '[U] Purchase Order Number [WIDENED per WIDENING-POLICY.md: SAP EKKO-EBELN is CHAR(10); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_purchase_receipt_document.vendor_id IS '[I] Vendor ID [WIDENED per WIDENING-POLICY.md: SAP EKKO-LIFNR is CHAR(10); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_purchase_receipt_document.po_date IS '[U] PO Date';
COMMENT ON COLUMN cdk_purchase_receipt_document.po_line_number IS '[U] PO Line Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.part_number IS '[I] Part Number [WIDENED per WIDENING-POLICY.md: SAP EKPO-MATNR is CHAR(18); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_purchase_receipt_document.quantity_ordered IS '[U] Quantity Ordered';
COMMENT ON COLUMN cdk_purchase_receipt_document.quantity_received IS '[I] Quantity Received';
COMMENT ON COLUMN cdk_purchase_receipt_document.receipt_document_number IS '[U] Receipt (GR) Document Number [WIDENED per WIDENING-POLICY.md: SAP MKPF-MBLNR is CHAR(10); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_purchase_receipt_document.receipt_date IS '[I] Receipt Date';
COMMENT ON COLUMN cdk_purchase_receipt_document.asn_number IS '[I] Advance Ship Notice (ASN) Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.invoice_number IS '[I] Vendor Invoice Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.unit_cost IS '[U] Unit Cost (Invoiced)';
COMMENT ON COLUMN cdk_purchase_receipt_document.three_way_match_status IS '[I] Three-Way Match Status (values: MATCHED=PO, receipt, and invoice all agree; QTY_VARIANCE=Quantity variance between receipt and invoice; PRICE_VARIANCE=Price variance between PO and invoice; UNMATCHED=Not yet matched)';
COMMENT ON COLUMN cdk_purchase_receipt_document.ap_posting_gl_account IS '[I] AP Posting GL Account';
COMMENT ON COLUMN cdk_purchase_receipt_document.movement_type_sap_analogue IS '[I] Movement Type (SAP Analogue) [WIDENED per WIDENING-POLICY.md: SAP MSEG-BWART is CHAR(3); DDL emits source-native 4]';
COMMENT ON COLUMN cdk_purchase_receipt_document._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_purchase_receipt_document._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_purchase_receipt_document._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_purchase_receipt_document._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_vendor_id FOREIGN KEY (vendor_id) REFERENCES cdk_vendor_master (vendor_id) NOT ENFORCED;
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number) NOT ENFORCED;
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_invoice_number FOREIGN KEY (invoice_number) REFERENCES cdk_vendor_master (vendor_id) NOT ENFORCED;
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_ap_posting_gl_account FOREIGN KEY (ap_posting_gl_account) REFERENCES cdk_gl_account_master (gl_account_number) NOT ENFORCED;
