-- cdk_ro_labour_line (ro-labour-line) -- RO Labour Line
-- one labour operation on an RO
-- SAP analogue: Confirmation/activity allocation line (COEP)
-- grain: one row per labour operation per RO
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_ro_labour_line (
    ro_labour_line_id VARCHAR(12) NOT NULL,
    amount NUMBER(13,2),
    created_date DATE,
    status_code VARCHAR(2),
    repair_order_number VARCHAR(12) NOT NULL,
    _rooftop_id VARCHAR(20),
    _extracted_at TIMESTAMP_NTZ,
    _source_route VARCHAR(16),
    _batch_id VARCHAR(64),
    PRIMARY KEY (ro_labour_line_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_ro_labour_line.ro_labour_line_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_ro_labour_line.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_ro_labour_line.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_ro_labour_line.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_ro_labour_line.repair_order_number IS '[D] which RO this labour line belongs to';
COMMENT ON COLUMN cdk_ro_labour_line._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_ro_labour_line._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_ro_labour_line._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_ro_labour_line._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_repair_order_number FOREIGN KEY (repair_order_number) REFERENCES cdk_repair_order (repair_order_number) NOT ENFORCED;
