-- cdk_vehicle_master (vehicle-master) -- Vehicle Master
-- Vehicle
-- SAP analogue: EQUI (Equipment Master) — closest SAP analogue for a serialized asset record
-- grain: one row per vehicle (VIN) per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_vehicle_master (
    vehicle_id VARCHAR(32) NOT NULL,
    vin VARCHAR(17) NOT NULL,
    license_plate_number VARCHAR(15),
    make_code VARCHAR(10),
    make VARCHAR(40),
    model_code VARCHAR(10),
    model VARCHAR(40),
    model_year NUMBER(38,0),
    exterior_color VARCHAR(30),
    mileage_value NUMBER(13,3),
    mileage_units VARCHAR(32),
    vehicle_status VARCHAR(32),
    date_delivered DATE,
    date_in_service DATE,
    warranty_expiration_date DATE,
    owner_href VARCHAR(255),
    primary_driver_href VARCHAR(255),
    stock_number VARCHAR(15),
    lot_location VARCHAR(20),
    ro_embedded_veh_id VARCHAR(32),
    ro_embedded_delivery_date DATE,
    ro_embedded_vehicle_color VARCHAR(30),
    ro_embedded_make_desc VARCHAR(40),
    ro_embedded_model_desc VARCHAR(40),
    is_sold_by_dealer BOOLEAN,
    _rooftop_id VARCHAR(20),
    _extracted_at TIMESTAMP_NTZ,
    _source_route VARCHAR(16),
    _batch_id VARCHAR(64),
    PRIMARY KEY (vehicle_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_vehicle_master.vehicle_id IS '[D] Vehicle ID';
COMMENT ON COLUMN cdk_vehicle_master.vin IS '[D] VIN';
COMMENT ON COLUMN cdk_vehicle_master.license_plate_number IS '[D] License Plate Number';
COMMENT ON COLUMN cdk_vehicle_master.make_code IS '[D] Make Code';
COMMENT ON COLUMN cdk_vehicle_master.make IS '[D] Make';
COMMENT ON COLUMN cdk_vehicle_master.model_code IS '[D] Model Code';
COMMENT ON COLUMN cdk_vehicle_master.model IS '[D] Model';
COMMENT ON COLUMN cdk_vehicle_master.model_year IS '[D] Model Year';
COMMENT ON COLUMN cdk_vehicle_master.exterior_color IS '[D] Exterior Color';
COMMENT ON COLUMN cdk_vehicle_master.mileage_value IS '[D] Mileage Value';
COMMENT ON COLUMN cdk_vehicle_master.mileage_units IS '[D] Mileage Units (values: MILES=Miles; KM=Kilometers)';
COMMENT ON COLUMN cdk_vehicle_master.vehicle_status IS '[D] Vehicle Status (values: new=New vehicle; used=Used vehicle; certified=Certified pre-owned)';
COMMENT ON COLUMN cdk_vehicle_master.date_delivered IS '[D] Date Delivered';
COMMENT ON COLUMN cdk_vehicle_master.date_in_service IS '[D] Date In Service';
COMMENT ON COLUMN cdk_vehicle_master.warranty_expiration_date IS '[D] Warranty Expiration Date';
COMMENT ON COLUMN cdk_vehicle_master.owner_href IS '[D] Owner Link (HATEOAS)';
COMMENT ON COLUMN cdk_vehicle_master.primary_driver_href IS '[D] Primary Driver Link (HATEOAS)';
COMMENT ON COLUMN cdk_vehicle_master.stock_number IS '[U] Stock Number';
COMMENT ON COLUMN cdk_vehicle_master.lot_location IS '[D] Lot Location';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_veh_id IS '[D] RO-Embedded Vehicle ID';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_delivery_date IS '[D] RO-Embedded Delivery Date';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_vehicle_color IS '[D] RO-Embedded Vehicle Color';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_make_desc IS '[D] RO-Embedded Make Description';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_model_desc IS '[D] RO-Embedded Model Description';
COMMENT ON COLUMN cdk_vehicle_master.is_sold_by_dealer IS '[D] Sold By This Dealer Flag';
COMMENT ON COLUMN cdk_vehicle_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_vehicle_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_vehicle_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_vehicle_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_vehicle_master ADD CONSTRAINT fk_cdk_vehicle_master_owner_href FOREIGN KEY (owner_href) REFERENCES cdk_customer_master (customer_id) NOT ENFORCED;
ALTER TABLE cdk_vehicle_master ADD CONSTRAINT fk_cdk_vehicle_master_primary_driver_href FOREIGN KEY (primary_driver_href) REFERENCES cdk_customer_master (customer_id) NOT ENFORCED;
ALTER TABLE cdk_vehicle_master ADD CONSTRAINT fk_cdk_vehicle_master_ro_embedded_veh_id FOREIGN KEY (ro_embedded_veh_id) REFERENCES cdk_vehicle_master (vehicle_id) NOT ENFORCED;
