-- cdk_vendor_master (vendor-master) -- Vendor Master
-- Vendor
-- SAP analogue: LFA1 (General Vendor Master) / LFB1 (Company Code Data)
-- grain: one row per vendor per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_vendor_master (
    vendor_id VARCHAR(20),
    vendor_name VARCHAR(80),
    remit_to_address_line1 VARCHAR(60),
    remit_to_city VARCHAR(40),
    remit_to_state VARCHAR(10),
    remit_to_postal_code VARCHAR(15),
    tax_id_1099 VARCHAR(20),
    gst_hst_number VARCHAR(20),
    vendor_class VARCHAR(32),
    payment_terms VARCHAR(20),
    ap_control_gl_account VARCHAR(10),
    vendor_status VARCHAR(32),
    _rooftop_id VARCHAR(20),
    _extracted_at TIMESTAMP_NTZ,
    _source_route VARCHAR(16),
    _batch_id VARCHAR(64),
    PRIMARY KEY (vendor_id)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on vendor_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_vendor_master.vendor_id IS '[I] Vendor ID';
COMMENT ON COLUMN cdk_vendor_master.vendor_name IS '[I] Vendor Name';
COMMENT ON COLUMN cdk_vendor_master.remit_to_address_line1 IS '[I] Remit-To Address Line 1';
COMMENT ON COLUMN cdk_vendor_master.remit_to_city IS '[I] Remit-To City';
COMMENT ON COLUMN cdk_vendor_master.remit_to_state IS '[I] Remit-To State';
COMMENT ON COLUMN cdk_vendor_master.remit_to_postal_code IS '[I] Remit-To Postal Code';
COMMENT ON COLUMN cdk_vendor_master.tax_id_1099 IS '[I] 1099 Tax ID';
COMMENT ON COLUMN cdk_vendor_master.gst_hst_number IS '[I] GST/HST Number';
COMMENT ON COLUMN cdk_vendor_master.vendor_class IS '[U] Vendor Classification (values: OEM=OEM/factory vendor (e.g. PACCAR); SUBLET=Sublet repair vendor; TRADE=Local trade vendor; OTHER=Other/general vendor)';
COMMENT ON COLUMN cdk_vendor_master.payment_terms IS '[I] Payment Terms';
COMMENT ON COLUMN cdk_vendor_master.ap_control_gl_account IS '[I] AP Control GL Account';
COMMENT ON COLUMN cdk_vendor_master.vendor_status IS '[U] Vendor Status (values: ACTIVE=Active vendor; HOLD=Payment hold; INACTIVE=Inactive/closed)';
COMMENT ON COLUMN cdk_vendor_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_vendor_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_vendor_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_vendor_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_vendor_master ADD CONSTRAINT fk_cdk_vendor_master_ap_control_gl_account FOREIGN KEY (ap_control_gl_account) REFERENCES cdk_gl_account_master (gl_account_number) NOT ENFORCED;
