-- cdk_warranty_claim (warranty-claim) -- Warranty Claim
-- Warranty Claim
-- SAP analogue: Not a native SAP object; closest conceptual analogue is a customer/OEM debit memo tied to a service notification (IW51/IW52) with its own receivable account
-- grain: one row per warranty claim
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_warranty_claim (
    claim_number VARCHAR(20),
    ro_number VARCHAR(20),
    vin VARCHAR(17),
    causal_part_number VARCHAR(20),
    claim_category_code VARCHAR(10),
    concern_text VARCHAR(1000),
    cause_text VARCHAR(1000),
    correction_text VARCHAR(1000),
    srt_code VARCHAR(10),
    claim_story_text VARCHAR(1000),
    campaign_number VARCHAR(20),
    failure_code VARCHAR(10),
    submission_window_days NUMBER(13,3),
    claim_type VARCHAR(32),
    claim_status VARCHAR(32),
    gl_account_claim_receivable VARCHAR(10),
    aging_bucket VARCHAR(32),
    claim_amount NUMBER(13,2),
    _rooftop_id VARCHAR(20),
    _extracted_at TIMESTAMP_NTZ,
    _source_route VARCHAR(16),
    _batch_id VARCHAR(64),
    PRIMARY KEY (claim_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on claim_number: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)
    -- NOT NULL withheld on ro_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on vin: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_warranty_claim.claim_number IS '[U] Warranty Claim Number [WIDENED per WIDENING-POLICY.md: SAP BSID-XBLNR is CHAR(16); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_warranty_claim.ro_number IS '[I] Source RO Number [WIDENED per WIDENING-POLICY.md: SAP AUFK-AUFNR is CHAR(12); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_warranty_claim.vin IS '[I] Vehicle VIN';
COMMENT ON COLUMN cdk_warranty_claim.causal_part_number IS '[I] Causal / Removed Part Number [WIDENED per WIDENING-POLICY.md: SAP MARA-MATNR is CHAR(18); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_warranty_claim.claim_category_code IS '[I] Claim Category Code';
COMMENT ON COLUMN cdk_warranty_claim.concern_text IS '[I] Concern Narrative';
COMMENT ON COLUMN cdk_warranty_claim.cause_text IS '[I] Cause Narrative';
COMMENT ON COLUMN cdk_warranty_claim.correction_text IS '[I] Correction Narrative';
COMMENT ON COLUMN cdk_warranty_claim.srt_code IS '[I] SRT (Standard Repair Time) Code [WIDENED per WIDENING-POLICY.md: SAP AFVC-STEUS is CHAR(4); DDL emits source-native 10]';
COMMENT ON COLUMN cdk_warranty_claim.claim_story_text IS '[I] Claim Story Text';
COMMENT ON COLUMN cdk_warranty_claim.campaign_number IS '[I] Campaign Number';
COMMENT ON COLUMN cdk_warranty_claim.failure_code IS '[I] Failure Code [WIDENED per WIDENING-POLICY.md: SAP QMFE-FEGRP is CHAR(8); DDL emits source-native 10]';
COMMENT ON COLUMN cdk_warranty_claim.submission_window_days IS '[I] Submission Window (Days)';
COMMENT ON COLUMN cdk_warranty_claim.claim_type IS '[I] Claim Type (values: QUICK=Quick Claim (pre-coded campaign/failure code); LONG=Long-form claim (manual narrative entry))';
COMMENT ON COLUMN cdk_warranty_claim.claim_status IS '[U] Claim Status (values: DRAFT=Draft (created from RO, not yet submitted); SUBMITTED=Submitted to PRWS; PAID=Factory paid; REJECTED=Factory rejected)';
COMMENT ON COLUMN cdk_warranty_claim.gl_account_claim_receivable IS '[I] GL Warranty Claims Receivable Account';
COMMENT ON COLUMN cdk_warranty_claim.aging_bucket IS '[I] Claim Aging Bucket (values: 0-30=0-30 days; 31-60=31-60 days; 61-90=61-90 days; 90+=90+ days)';
COMMENT ON COLUMN cdk_warranty_claim.claim_amount IS '[U] Claim Amount';
COMMENT ON COLUMN cdk_warranty_claim._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_warranty_claim._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_warranty_claim._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_warranty_claim._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_warranty_claim ADD CONSTRAINT fk_cdk_warranty_claim_ro_number FOREIGN KEY (ro_number) REFERENCES cdk_repair_order (ro_number) NOT ENFORCED;
ALTER TABLE cdk_warranty_claim ADD CONSTRAINT fk_cdk_warranty_claim_vin FOREIGN KEY (vin) REFERENCES cdk_vehicle_master (vin) NOT ENFORCED;
ALTER TABLE cdk_warranty_claim ADD CONSTRAINT fk_cdk_warranty_claim_causal_part_number FOREIGN KEY (causal_part_number) REFERENCES cdk_parts_master_inventory (part_number) NOT ENFORCED;
ALTER TABLE cdk_warranty_claim ADD CONSTRAINT fk_cdk_warranty_claim_gl_account_claim_receivable FOREIGN KEY (gl_account_claim_receivable) REFERENCES cdk_gl_account_master (gl_account_number) NOT ENFORCED;
