-- 000_all.sql -- rollup of every Lane F Postgres DDL file
-- generated 2026-07-29T06:42:20Z by schema/bin/gen_ddl.py from FIXTURE-DERIVED (schema/bin/fixture_fields.py) -- not the real field dictionary
-- Run this file to build the full load-ready schema in one pass.

-- cdk_dealer_rooftop_partition (dealer-rooftop-partition) -- Dealer / Rooftop Partition
-- which of the 9 stores this record belongs to
-- SAP analogue: Company Code (T001) / Plant (WERKS) plus a module-scoping flag
-- grain: one row per rooftop/department scope pairing
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_dealer_rooftop_partition (
    subscription_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (subscription_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_dealer_rooftop_partition.subscription_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_cost_centre_department (cost-centre-department) -- Cost Centre / Department
-- which part of the store a cost belongs to
-- SAP analogue: Cost centre / profit centre (CSKS/CEPC)
-- grain: one row per department per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_cost_centre_department (
    department_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (department_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_cost_centre_department.department_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_cost_centre_department.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_cost_centre_department.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_cost_centre_department.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_cost_centre_department._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_cost_centre_department._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_cost_centre_department._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_cost_centre_department._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_customer_master (customer-master) -- Customer Master
-- the customer record — fleet account, walk-in owner, or company
-- SAP analogue: KNA1 / KNB1 / KNVV — customer master, general + company-code + sales views
-- grain: one row per customer per rooftop
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_customer_master (
    customer_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (customer_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_customer_master.customer_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_customer_master.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_customer_master.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_customer_master.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_customer_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_customer_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_customer_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_customer_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_vehicle_master (vehicle-master) -- Vehicle / Unit Master
-- the truck or unit record, keyed by VIN
-- SAP analogue: Equipment master (EQUI), serialized — VIN as equipment number
-- grain: one row per VIN
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_vehicle_master (
    vin varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (vin)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_vehicle_master.vin IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_vehicle_master.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_vehicle_master.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_vehicle_master.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_vehicle_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_vehicle_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_vehicle_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_vehicle_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_employee_master (employee-master) -- Employee / Technician Identifiers
-- the tech or advisor record
-- SAP analogue: HR-adjacent Z-fields on transaction tables (no clean HR analogue)
-- grain: one row per employee per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_employee_master (
    employee_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (employee_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_employee_master.employee_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_employee_master.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_employee_master.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_employee_master.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_employee_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_employee_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_employee_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_employee_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_vendor_master (vendor-master) -- Vendor / Supplier Master
-- the supplier record for parts and services purchased
-- SAP analogue: LFA1 / LFB1 — vendor master, general + company-code data
-- grain: one row per vendor
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_vendor_master (
    vendor_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (vendor_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_vendor_master.vendor_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_vendor_master.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_vendor_master.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_vendor_master.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_vendor_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_vendor_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_vendor_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_vendor_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_gl_account_master (gl-account-master) -- GL Account Master
-- the chart of accounts entry
-- SAP analogue: SKA1 / SKB1 — chart of accounts + company-code GL segment
-- grain: one row per GL account per department suffix
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_gl_account_master (
    gl_account_number varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (gl_account_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_gl_account_master.gl_account_number IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_gl_account_master.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_gl_account_master.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_gl_account_master.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_gl_account_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_gl_account_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_gl_account_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_gl_account_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_accounting_schedule (accounting-schedule) -- Accounting Schedule
-- the open-item subledger behind one GL control account
-- SAP analogue: Reconciliation-account subledger / open-item list
-- grain: one row per schedule control-key entry
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_accounting_schedule (
    schedule_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (schedule_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_accounting_schedule.schedule_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_accounting_schedule.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_accounting_schedule.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_accounting_schedule.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_accounting_schedule._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_accounting_schedule._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_accounting_schedule._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_accounting_schedule._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_gl_journal_posting (gl-journal-posting) -- GL Journal / Posting
-- one line of a journal entry
-- SAP analogue: BKPF/BSEG — accounting document header + line items
-- grain: one row per journal line
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_gl_journal_posting (
    journal_line_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (journal_line_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_gl_journal_posting.journal_line_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_gl_journal_posting.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_gl_journal_posting.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_gl_journal_posting.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_gl_journal_posting._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_gl_journal_posting._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_gl_journal_posting._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_gl_journal_posting._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_repair_order (repair-order) -- Repair Order
-- the RO — the work order for a truck
-- SAP analogue: Internal order (AUFK/COEP) with a payer settlement rule
-- grain: one row per repair order
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_repair_order (
    repair_order_number varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (repair_order_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_repair_order.repair_order_number IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_repair_order.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_repair_order.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_repair_order.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_repair_order._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_repair_order._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_repair_order._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_repair_order._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_ro_labour_line (ro-labour-line) -- RO Labour Line
-- one labour operation on an RO
-- SAP analogue: Confirmation/activity allocation line (COEP)
-- grain: one row per labour operation per RO
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_ro_labour_line (
    ro_labour_line_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    repair_order_number varchar(12) NOT NULL,
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (ro_labour_line_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_ro_labour_line.ro_labour_line_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_ro_labour_line.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_ro_labour_line.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_ro_labour_line.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_ro_labour_line.repair_order_number IS '[D] which RO this labour line belongs to';
COMMENT ON COLUMN cdk_ro_labour_line._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_ro_labour_line._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_ro_labour_line._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_ro_labour_line._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_repair_order_number FOREIGN KEY (repair_order_number) REFERENCES cdk_repair_order (repair_order_number);

-- cdk_ro_part_line (ro-part-line) -- RO Part Line
-- one part consumed on an RO
-- SAP analogue: Goods movement / material consumption line (MSEG)
-- grain: one row per part line per RO
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_ro_part_line (
    ro_part_line_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (ro_part_line_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_ro_part_line.ro_part_line_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_ro_part_line.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_ro_part_line.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_ro_part_line.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_ro_part_line._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_ro_part_line._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_ro_part_line._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_ro_part_line._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_parts_master_inventory (parts-master-inventory) -- Parts Master / Inventory
-- the part number record and its on-hand position
-- SAP analogue: MARA/MARC/MBEW combined
-- grain: one row per part number per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_parts_master_inventory (
    part_number varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (part_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_parts_master_inventory.part_number IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_parts_master_inventory.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_parts_master_inventory.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_parts_master_inventory.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_parts_master_inventory._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_parts_master_inventory._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_parts_master_inventory._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_parts_master_inventory._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_parts_order_supersession (parts-order-supersession) -- Parts Order + Supersession
-- a parts order line and its supersession chain
-- SAP analogue: Purchase order (EKKO/EKPO) + material supersession chain
-- grain: one row per ordered part line
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_parts_order_supersession (
    order_line_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (order_line_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_parts_order_supersession.order_line_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_parts_order_supersession.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_parts_order_supersession.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_parts_order_supersession.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_parts_order_supersession._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_parts_order_supersession._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_parts_order_supersession._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_parts_order_supersession._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_parts_pick_ticket (parts-pick-ticket) -- Parts Pick Ticket
-- the pick slip tied to an RO parts line
-- SAP analogue: Reservation / goods issue slip (MB1A-style)
-- grain: one row per pick ticket line
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_parts_pick_ticket (
    pick_ticket_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (pick_ticket_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_parts_pick_ticket.pick_ticket_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_parts_pick_ticket.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_parts_pick_ticket.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_parts_pick_ticket.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_parts_pick_ticket._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_parts_pick_ticket._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_parts_pick_ticket._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_parts_pick_ticket._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_counter_parts_sale (counter-parts-sale) -- Counter / Parts Sale
-- a cash or wholesale parts sale at the counter
-- SAP analogue: Sales order + billing document (VBAK/VBRK)
-- grain: one row per counter sale line
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_counter_parts_sale (
    sale_line_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (sale_line_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_counter_parts_sale.sale_line_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_counter_parts_sale.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_counter_parts_sale.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_counter_parts_sale.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_counter_parts_sale._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_counter_parts_sale._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_counter_parts_sale._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_counter_parts_sale._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_deal_jacket_vehicle_sale (deal-jacket-vehicle-sale) -- Deal Jacket / Vehicle Sale
-- the file for one truck sale
-- SAP analogue: Sales order + billing document (VBAK/VBRK) + F&I lines
-- grain: one row per deal jacket
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_deal_jacket_vehicle_sale (
    deal_number varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (deal_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.deal_number IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_technician_time_punch (technician-time-punch) -- Technician Time Punch
-- one clock in/out event against an RO labour line
-- SAP analogue: Time confirmation (CATS-style) feeding activity allocation
-- grain: one row per punch event
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_technician_time_punch (
    punch_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (punch_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_technician_time_punch.punch_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_technician_time_punch.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_technician_time_punch.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_technician_time_punch.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_technician_time_punch._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_technician_time_punch._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_technician_time_punch._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_technician_time_punch._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_work_in_process (work-in-process) -- Work-in-Process
-- an RO still open, carried as WIP on the balance sheet
-- SAP analogue: WIP account tied to internal order settlement
-- grain: one row per open RO per reporting date
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_work_in_process (
    wip_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (wip_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_work_in_process.wip_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_work_in_process.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_work_in_process.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_work_in_process.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_work_in_process._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_work_in_process._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_work_in_process._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_work_in_process._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_warranty_claim (warranty-claim) -- Warranty Claim
-- a factory warranty claim filed against an RO
-- SAP analogue: Debit memo / claims-management document vs. factory receivable
-- grain: one row per warranty claim
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_warranty_claim (
    claim_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (claim_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_warranty_claim.claim_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_warranty_claim.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_warranty_claim.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_warranty_claim.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_warranty_claim._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_warranty_claim._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_warranty_claim._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_warranty_claim._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_purchase_receipt_document (purchase-receipt-document) -- Purchase / Receipt Document
-- a vendor invoice or receipt document
-- SAP analogue: Purchase order + goods receipt (EKKO/EKBE), 3-way match
-- grain: one row per receipt document line
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_purchase_receipt_document (
    receipt_document_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (receipt_document_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_purchase_receipt_document.receipt_document_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_purchase_receipt_document.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_purchase_receipt_document.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_purchase_receipt_document.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_purchase_receipt_document._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_purchase_receipt_document._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_purchase_receipt_document._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_purchase_receipt_document._batch_id IS '[D] the extract run/batch identifier this row landed with';
