-- 000_all.sql -- rollup of every Lane F Postgres DDL file
-- generated 2026-07-29T07:01:53Z by schema/bin/gen_ddl.py from docs/model/fields.json
-- Run this file to build the full load-ready schema in one pass.

-- cdk_dealer_rooftop_partition (dealer-rooftop-partition) -- Dealer Rooftop Partition
-- Rooftop / Store / Company
-- SAP analogue: Company Code (Buchungskreis) / Client (Mandant)
-- grain: one row per rooftop-department binding (Subscription-Id x Department-Id)
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_dealer_rooftop_partition (
    subscription_id varchar(64) NOT NULL,
    department_id varchar(32) NOT NULL,
    request_id varchar(64) NOT NULL,
    company_number varchar(10),
    cmf_client_number varchar(10),
    dms_type varchar(20) NOT NULL,
    rooftop_name varchar(120),
    rooftop_address varchar(255),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (subscription_id, department_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_dealer_rooftop_partition.subscription_id IS '[D] Subscription-Id';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.department_id IS '[D] Department-Id';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.request_id IS '[D] Request-Id';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.company_number IS '[U] Co #';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.cmf_client_number IS '[U] Client #';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.dms_type IS '[D] DMS Type (values: Accounting=Accounting DMS module; Finance=Finance/F&I DMS module; Inventory=Vehicle inventory DMS module; Parts=Parts DMS module; Service=Service DMS module)';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.rooftop_name IS '[I] Dealer Name';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.rooftop_address IS '[I] Dealer Address';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_cost_centre_department (cost-centre-department) -- Cost Centre / Department
-- Department
-- SAP analogue: Cost Center (Kostenstelle) / Profit Center
-- grain: one row per department code per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_cost_centre_department (
    department_code varchar(2) NOT NULL,
    department_id varchar(32) NOT NULL,
    dms_type varchar(32) NOT NULL,
    department_name varchar(60),
    schedule_index varchar(32),
    absorption_rate_is_report_only boolean,
    cost_center_type varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (department_code)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_cost_centre_department.department_code IS '[D] Dept # (values: 01=New Vehicles; 02=Used Vehicles; 03=Lease & Rental; 04=Finance & Insurance (F&I); 05=Mechanical / Service; 06=Body Shop; 07=Parts & Accessories; 09=General & Administrative)';
COMMENT ON COLUMN cdk_cost_centre_department.department_id IS '[D] Department-Id';
COMMENT ON COLUMN cdk_cost_centre_department.dms_type IS '[D] Bound DMS Type (values: Accounting=Accounting; Finance=Finance; Inventory=Inventory; Parts=Parts; Service=Service)';
COMMENT ON COLUMN cdk_cost_centre_department.department_name IS '[I] Department Name';
COMMENT ON COLUMN cdk_cost_centre_department.schedule_index IS '[U] Schedule Index Type (values: 0=No Schedule; 1=Vehicle Inventory; 2=Accounts Receivable; 3=Accounts Payable; 4=Miscellaneous Balance Forward; 5=Miscellaneous Detail Forward; 6=Combination)';
COMMENT ON COLUMN cdk_cost_centre_department.absorption_rate_is_report_only IS '[I] Absorption Rate — Reporting Only';
COMMENT ON COLUMN cdk_cost_centre_department.cost_center_type IS '[I] Cost Center Type (values: FIXED=Fixed operations (Service/Parts/Body Shop); VARIABLE=Variable operations (New/Used vehicle sales, F&I))';
COMMENT ON COLUMN cdk_cost_centre_department._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_cost_centre_department._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_cost_centre_department._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_cost_centre_department._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_customer_master (customer-master) -- Customer Master
-- Customer
-- SAP analogue: KNA1 (General Customer Master) / KNB1 (Company Code Data)
-- grain: one row per customer per rooftop
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_customer_master (
    customer_id varchar(32) NOT NULL,
    host_item_id varchar(32),
    first_name varchar(40),
    middle_name varchar(40),
    last_name varchar(40),
    full_name varchar(120),
    company_name varchar(80),
    name_suffix varchar(10),
    title varchar(10),
    secondary_first_name varchar(40),
    secondary_last_name varchar(40),
    secondary_full_name varchar(120),
    secondary_company_name varchar(80),
    birth_day varchar(2),
    birth_month varchar(2),
    birth_year varchar(4),
    address_line1 varchar(60),
    address_line2 varchar(60),
    city varchar(40),
    county varchar(40),
    state varchar(10),
    postal_code varchar(15),
    country varchar(40),
    primary_phone varchar(20),
    home_phone varchar(20),
    secondary_home_phone varchar(20),
    mobile_phone varchar(20),
    business_phone varchar(20),
    business_phone_ext varchar(10),
    home_fax varchar(20),
    work_fax varchar(20),
    pager_number varchar(20),
    text_message_phone varchar(20),
    text_message_carrier varchar(30),
    email_address varchar(120),
    email_type varchar(32),
    preferred_contact_method varchar(32),
    preferred_contact varchar(32),
    preferred_day varchar(32),
    preferred_time varchar(32),
    block_email_flag boolean,
    block_mail_flag boolean,
    block_phone_flag boolean,
    gender varchar(32),
    employer varchar(80),
    language_preference varchar(10),
    comment varchar(255),
    comment_date date,
    date_added date,
    last_updated date,
    parts_flag boolean,
    parts_type varchar(32),
    parts_counter_code varchar(10),
    service_customer_code varchar(2),
    mailability_index varchar(2),
    name_control_code varchar(4),
    tax_code varchar(10),
    default_sale_type varchar(10),
    is_delete_data_flag boolean,
    delete_data_date date,
    delete_data_time varchar(8),
    opt_out_flag boolean,
    opt_out_date date,
    opt_out_time varchar(8),
    casl_consent_timestamp timestamptz,
    overdue_30_days numeric(13,2),
    overdue_60_days numeric(13,2),
    overdue_90_days numeric(13,2),
    overdue_120_days numeric(13,2),
    current_balance numeric(13,2),
    credit_limit numeric(13,2),
    current_due numeric(13,2),
    insurance_policy_number varchar(40),
    insurance_policy_expiration date,
    insurance_company_name varchar(80),
    insurance_agent_name varchar(80),
    special_instructions_line1 varchar(80),
    special_instructions_line2 varchar(80),
    special_instructions_line3 varchar(80),
    special_instructions_line4 varchar(80),
    special_instructions_line5 varchar(80),
    crm_customer_id varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (customer_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_customer_master.customer_id IS '[D] Customer ID';
COMMENT ON COLUMN cdk_customer_master.host_item_id IS '[D] Host Item ID';
COMMENT ON COLUMN cdk_customer_master.first_name IS '[D] First Name';
COMMENT ON COLUMN cdk_customer_master.middle_name IS '[D] Middle Name';
COMMENT ON COLUMN cdk_customer_master.last_name IS '[D] Last Name';
COMMENT ON COLUMN cdk_customer_master.full_name IS '[D] Full Name';
COMMENT ON COLUMN cdk_customer_master.company_name IS '[D] Company Name';
COMMENT ON COLUMN cdk_customer_master.name_suffix IS '[D] Name Suffix';
COMMENT ON COLUMN cdk_customer_master.title IS '[D] Title';
COMMENT ON COLUMN cdk_customer_master.secondary_first_name IS '[D] Secondary First Name';
COMMENT ON COLUMN cdk_customer_master.secondary_last_name IS '[D] Secondary Last Name';
COMMENT ON COLUMN cdk_customer_master.secondary_full_name IS '[D] Secondary Full Name';
COMMENT ON COLUMN cdk_customer_master.secondary_company_name IS '[D] Secondary Company Name';
COMMENT ON COLUMN cdk_customer_master.birth_day IS '[D] Birth Day';
COMMENT ON COLUMN cdk_customer_master.birth_month IS '[D] Birth Month';
COMMENT ON COLUMN cdk_customer_master.birth_year IS '[D] Birth Year';
COMMENT ON COLUMN cdk_customer_master.address_line1 IS '[D] Address Line 1';
COMMENT ON COLUMN cdk_customer_master.address_line2 IS '[D] Address Line 2';
COMMENT ON COLUMN cdk_customer_master.city IS '[D] City';
COMMENT ON COLUMN cdk_customer_master.county IS '[D] County';
COMMENT ON COLUMN cdk_customer_master.state IS '[D] State';
COMMENT ON COLUMN cdk_customer_master.postal_code IS '[D] Postal Code';
COMMENT ON COLUMN cdk_customer_master.country IS '[D] Country';
COMMENT ON COLUMN cdk_customer_master.primary_phone IS '[D] Primary Phone';
COMMENT ON COLUMN cdk_customer_master.home_phone IS '[D] Home Phone';
COMMENT ON COLUMN cdk_customer_master.secondary_home_phone IS '[D] Secondary Home Phone';
COMMENT ON COLUMN cdk_customer_master.mobile_phone IS '[D] Mobile Phone';
COMMENT ON COLUMN cdk_customer_master.business_phone IS '[D] Business Phone';
COMMENT ON COLUMN cdk_customer_master.business_phone_ext IS '[D] Business Phone Ext';
COMMENT ON COLUMN cdk_customer_master.home_fax IS '[D] Home Fax';
COMMENT ON COLUMN cdk_customer_master.work_fax IS '[D] Work Fax';
COMMENT ON COLUMN cdk_customer_master.pager_number IS '[D] Pager Number';
COMMENT ON COLUMN cdk_customer_master.text_message_phone IS '[D] Text Message Phone';
COMMENT ON COLUMN cdk_customer_master.text_message_carrier IS '[D] Text Message Carrier';
COMMENT ON COLUMN cdk_customer_master.email_address IS '[D] Email Address';
COMMENT ON COLUMN cdk_customer_master.email_type IS '[D] Email Type (values: CELL=Cell; HOME=Home (default); WORK=Work; PDA/LAPTOP=PDA/Laptop; VEHICLE=Vehicle; OTHER=Other; NA=Non-applicable; CD=Customer declined to add)';
COMMENT ON COLUMN cdk_customer_master.preferred_contact_method IS '[D] Preferred Contact Method (values: B=Work FAX; D=Do Not Disturb/Contact; E=Email address; F=Home FAX; M=Postal mail; P=Pager; T=Main Telephone; X=Text message)';
COMMENT ON COLUMN cdk_customer_master.preferred_contact IS '[D] Preferred Contact (record-level) (values: C=Cellular/mobile phone; E=Email; F=Home Fax; H=Home Phone; M=Mail; P=Pager; W=Work phone; null=No preference)';
COMMENT ON COLUMN cdk_customer_master.preferred_day IS '[D] Preferred Day (values: 1=Monday; 2=Tuesday; 3=Wednesday; 4=Thursday; 5=Friday; 6=Saturday; 7=Sunday)';
COMMENT ON COLUMN cdk_customer_master.preferred_time IS '[D] Preferred Time (values: AM=Morning; PM=Afternoon/evening)';
COMMENT ON COLUMN cdk_customer_master.block_email_flag IS '[D] Block Email Flag';
COMMENT ON COLUMN cdk_customer_master.block_mail_flag IS '[D] Block Mail Flag';
COMMENT ON COLUMN cdk_customer_master.block_phone_flag IS '[D] Block Phone Flag';
COMMENT ON COLUMN cdk_customer_master.gender IS '[D] Gender (values: F=Female; M=Male)';
COMMENT ON COLUMN cdk_customer_master.employer IS '[D] Employer';
COMMENT ON COLUMN cdk_customer_master.language_preference IS '[D] Language Preference';
COMMENT ON COLUMN cdk_customer_master.comment IS '[D] Comment';
COMMENT ON COLUMN cdk_customer_master.comment_date IS '[D] Comment Date';
COMMENT ON COLUMN cdk_customer_master.date_added IS '[D] Date Added';
COMMENT ON COLUMN cdk_customer_master.last_updated IS '[D] Last Updated';
COMMENT ON COLUMN cdk_customer_master.parts_flag IS '[D] Parts Customer Flag';
COMMENT ON COLUMN cdk_customer_master.parts_type IS '[D] Parts Type (values: W=Wholesale customer; null=No type)';
COMMENT ON COLUMN cdk_customer_master.parts_counter_code IS '[D] Parts Counter Code';
COMMENT ON COLUMN cdk_customer_master.service_customer_code IS '[D] Service Customer Code (values: S=Service-only (non-AR/Parts) customer)';
COMMENT ON COLUMN cdk_customer_master.mailability_index IS '[D] Mailability Index (values: 1-9=Primary partner mailability index tiers; X=Excluded/undeliverable)';
COMMENT ON COLUMN cdk_customer_master.name_control_code IS '[D] Name Control Code';
COMMENT ON COLUMN cdk_customer_master.tax_code IS '[D] Sold-To Tax Code';
COMMENT ON COLUMN cdk_customer_master.default_sale_type IS '[D] Default Sale Type';
COMMENT ON COLUMN cdk_customer_master.is_delete_data_flag IS '[D] CCPA Delete-Data Flag';
COMMENT ON COLUMN cdk_customer_master.delete_data_date IS '[D] CCPA Delete Data Date';
COMMENT ON COLUMN cdk_customer_master.delete_data_time IS '[D] CCPA Delete Data Time';
COMMENT ON COLUMN cdk_customer_master.opt_out_flag IS '[D] Privacy Opt-Out Flag';
COMMENT ON COLUMN cdk_customer_master.opt_out_date IS '[D] Privacy Opt-Out Date';
COMMENT ON COLUMN cdk_customer_master.opt_out_time IS '[D] Privacy Opt-Out Time';
COMMENT ON COLUMN cdk_customer_master.casl_consent_timestamp IS '[U] CASL Consent Timestamp (gap)';
COMMENT ON COLUMN cdk_customer_master.overdue_30_days IS '[D] Balance Over 30 Days';
COMMENT ON COLUMN cdk_customer_master.overdue_60_days IS '[D] Balance Over 60 Days';
COMMENT ON COLUMN cdk_customer_master.overdue_90_days IS '[D] Balance Over 90 Days';
COMMENT ON COLUMN cdk_customer_master.overdue_120_days IS '[D] Balance Over 120 Days';
COMMENT ON COLUMN cdk_customer_master.current_balance IS '[D] Current Balance';
COMMENT ON COLUMN cdk_customer_master.credit_limit IS '[D] Credit Limit';
COMMENT ON COLUMN cdk_customer_master.current_due IS '[D] Current Amount Due';
COMMENT ON COLUMN cdk_customer_master.insurance_policy_number IS '[D] Insurance Policy Number';
COMMENT ON COLUMN cdk_customer_master.insurance_policy_expiration IS '[D] Insurance Policy Expiration';
COMMENT ON COLUMN cdk_customer_master.insurance_company_name IS '[D] Insurance Company Name';
COMMENT ON COLUMN cdk_customer_master.insurance_agent_name IS '[D] Insurance Agent Name';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line1 IS '[D] Special Instructions Line 1';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line2 IS '[D] Special Instructions Line 2';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line3 IS '[D] Special Instructions Line 3';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line4 IS '[D] Special Instructions Line 4';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line5 IS '[D] Special Instructions Line 5';
COMMENT ON COLUMN cdk_customer_master.crm_customer_id IS '[D] CRM Customer ID (Customers API v1)';
COMMENT ON COLUMN cdk_customer_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_customer_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_customer_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_customer_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_customer_master ADD CONSTRAINT fk_cdk_customer_master_crm_customer_id FOREIGN KEY (crm_customer_id) REFERENCES cdk_customer_master (customer_id);

-- cdk_vehicle_master (vehicle-master) -- Vehicle Master
-- Vehicle
-- SAP analogue: EQUI (Equipment Master) — closest SAP analogue for a serialized asset record
-- grain: one row per vehicle (VIN) per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_vehicle_master (
    vehicle_id varchar(32) NOT NULL,
    vin varchar(17) NOT NULL,
    license_plate_number varchar(15),
    make_code varchar(10),
    make varchar(40),
    model_code varchar(10),
    model varchar(40),
    model_year bigint,
    exterior_color varchar(30),
    mileage_value numeric(13,3),
    mileage_units varchar(32),
    vehicle_status varchar(32),
    date_delivered date,
    date_in_service date,
    warranty_expiration_date date,
    owner_href varchar(255),
    primary_driver_href varchar(255),
    stock_number varchar(15),
    lot_location varchar(20),
    ro_embedded_veh_id varchar(32),
    ro_embedded_delivery_date date,
    ro_embedded_vehicle_color varchar(30),
    ro_embedded_make_desc varchar(40),
    ro_embedded_model_desc varchar(40),
    is_sold_by_dealer boolean,
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (vehicle_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_vehicle_master.vehicle_id IS '[D] Vehicle ID';
COMMENT ON COLUMN cdk_vehicle_master.vin IS '[D] VIN';
COMMENT ON COLUMN cdk_vehicle_master.license_plate_number IS '[D] License Plate Number';
COMMENT ON COLUMN cdk_vehicle_master.make_code IS '[D] Make Code';
COMMENT ON COLUMN cdk_vehicle_master.make IS '[D] Make';
COMMENT ON COLUMN cdk_vehicle_master.model_code IS '[D] Model Code';
COMMENT ON COLUMN cdk_vehicle_master.model IS '[D] Model';
COMMENT ON COLUMN cdk_vehicle_master.model_year IS '[D] Model Year';
COMMENT ON COLUMN cdk_vehicle_master.exterior_color IS '[D] Exterior Color';
COMMENT ON COLUMN cdk_vehicle_master.mileage_value IS '[D] Mileage Value';
COMMENT ON COLUMN cdk_vehicle_master.mileage_units IS '[D] Mileage Units (values: MILES=Miles; KM=Kilometers)';
COMMENT ON COLUMN cdk_vehicle_master.vehicle_status IS '[D] Vehicle Status (values: new=New vehicle; used=Used vehicle; certified=Certified pre-owned)';
COMMENT ON COLUMN cdk_vehicle_master.date_delivered IS '[D] Date Delivered';
COMMENT ON COLUMN cdk_vehicle_master.date_in_service IS '[D] Date In Service';
COMMENT ON COLUMN cdk_vehicle_master.warranty_expiration_date IS '[D] Warranty Expiration Date';
COMMENT ON COLUMN cdk_vehicle_master.owner_href IS '[D] Owner Link (HATEOAS)';
COMMENT ON COLUMN cdk_vehicle_master.primary_driver_href IS '[D] Primary Driver Link (HATEOAS)';
COMMENT ON COLUMN cdk_vehicle_master.stock_number IS '[U] Stock Number';
COMMENT ON COLUMN cdk_vehicle_master.lot_location IS '[D] Lot Location';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_veh_id IS '[D] RO-Embedded Vehicle ID';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_delivery_date IS '[D] RO-Embedded Delivery Date';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_vehicle_color IS '[D] RO-Embedded Vehicle Color';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_make_desc IS '[D] RO-Embedded Make Description';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_model_desc IS '[D] RO-Embedded Model Description';
COMMENT ON COLUMN cdk_vehicle_master.is_sold_by_dealer IS '[D] Sold By This Dealer Flag';
COMMENT ON COLUMN cdk_vehicle_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_vehicle_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_vehicle_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_vehicle_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_vehicle_master ADD CONSTRAINT fk_cdk_vehicle_master_owner_href FOREIGN KEY (owner_href) REFERENCES cdk_customer_master (customer_id);
ALTER TABLE cdk_vehicle_master ADD CONSTRAINT fk_cdk_vehicle_master_primary_driver_href FOREIGN KEY (primary_driver_href) REFERENCES cdk_customer_master (customer_id);
ALTER TABLE cdk_vehicle_master ADD CONSTRAINT fk_cdk_vehicle_master_ro_embedded_veh_id FOREIGN KEY (ro_embedded_veh_id) REFERENCES cdk_vehicle_master (vehicle_id);

-- cdk_employee_master (employee-master) -- Employee Master
-- Employee
-- SAP analogue: PA0001 / PA0002 (HR master infotypes) — closest SAP analogue
-- grain: one row per employee per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_employee_master (
    employee_key varchar(24),
    service_advisor_number bigint,
    cashier_id varchar(10),
    booker_number bigint,
    story_employee_number varchar(10),
    technician_ids varchar(40),
    comeback_service_advisor varchar(10),
    comeback_technician varchar(10),
    hours_technician_id bigint,
    parts_counter_employee_id bigint,
    outside_salesman_id bigint,
    punch_technician_id bigint,
    discount_user_id varchar(20),
    discount_applied_by varchar(20),
    manager_override_id varchar(20),
    lookup_technician_id varchar(10),
    lookup_service_advisor_id varchar(10),
    employee_name varchar(80),
    employee_department varchar(10),
    employee_status varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (employee_key)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on employee_key: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_employee_master.employee_key IS '[U] the one person behind all these different ID columns';
COMMENT ON COLUMN cdk_employee_master.service_advisor_number IS '[D] Service Advisor Number';
COMMENT ON COLUMN cdk_employee_master.cashier_id IS '[D] Cashier ID';
COMMENT ON COLUMN cdk_employee_master.booker_number IS '[D] Booker Number';
COMMENT ON COLUMN cdk_employee_master.story_employee_number IS '[D] Story Employee Number';
COMMENT ON COLUMN cdk_employee_master.technician_ids IS '[D] Technician ID(s)';
COMMENT ON COLUMN cdk_employee_master.comeback_service_advisor IS '[D] Comeback Service Advisor';
COMMENT ON COLUMN cdk_employee_master.comeback_technician IS '[D] Comeback Technician';
COMMENT ON COLUMN cdk_employee_master.hours_technician_id IS '[D] Hours-Detail Technician ID';
COMMENT ON COLUMN cdk_employee_master.parts_counter_employee_id IS '[D] Parts Counter Employee ID';
COMMENT ON COLUMN cdk_employee_master.outside_salesman_id IS '[D] Outside Salesman ID';
COMMENT ON COLUMN cdk_employee_master.punch_technician_id IS '[D] Punch Clock Technician ID';
COMMENT ON COLUMN cdk_employee_master.discount_user_id IS '[D] Discount User ID';
COMMENT ON COLUMN cdk_employee_master.discount_applied_by IS '[D] Discount Applied By';
COMMENT ON COLUMN cdk_employee_master.manager_override_id IS '[D] Manager Override ID';
COMMENT ON COLUMN cdk_employee_master.lookup_technician_id IS '[I] Technician Lookup ID';
COMMENT ON COLUMN cdk_employee_master.lookup_service_advisor_id IS '[I] Service Advisor Lookup ID';
COMMENT ON COLUMN cdk_employee_master.employee_name IS '[U] Employee Name';
COMMENT ON COLUMN cdk_employee_master.employee_department IS '[U] Employee Department';
COMMENT ON COLUMN cdk_employee_master.employee_status IS '[U] Employee Active/Terminated Status (values: ACTIVE=Active employee; TERMINATED=Terminated employee)';
COMMENT ON COLUMN cdk_employee_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_employee_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_employee_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_employee_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_vendor_master (vendor-master) -- Vendor Master
-- Vendor
-- SAP analogue: LFA1 (General Vendor Master) / LFB1 (Company Code Data)
-- grain: one row per vendor per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_vendor_master (
    vendor_id varchar(20),
    vendor_name varchar(80),
    remit_to_address_line1 varchar(60),
    remit_to_city varchar(40),
    remit_to_state varchar(10),
    remit_to_postal_code varchar(15),
    tax_id_1099 varchar(20),
    gst_hst_number varchar(20),
    vendor_class varchar(32),
    payment_terms varchar(20),
    ap_control_gl_account varchar(10),
    vendor_status varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (vendor_id)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on vendor_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_vendor_master.vendor_id IS '[I] Vendor ID';
COMMENT ON COLUMN cdk_vendor_master.vendor_name IS '[I] Vendor Name';
COMMENT ON COLUMN cdk_vendor_master.remit_to_address_line1 IS '[I] Remit-To Address Line 1';
COMMENT ON COLUMN cdk_vendor_master.remit_to_city IS '[I] Remit-To City';
COMMENT ON COLUMN cdk_vendor_master.remit_to_state IS '[I] Remit-To State';
COMMENT ON COLUMN cdk_vendor_master.remit_to_postal_code IS '[I] Remit-To Postal Code';
COMMENT ON COLUMN cdk_vendor_master.tax_id_1099 IS '[I] 1099 Tax ID';
COMMENT ON COLUMN cdk_vendor_master.gst_hst_number IS '[I] GST/HST Number';
COMMENT ON COLUMN cdk_vendor_master.vendor_class IS '[U] Vendor Classification (values: OEM=OEM/factory vendor (e.g. PACCAR); SUBLET=Sublet repair vendor; TRADE=Local trade vendor; OTHER=Other/general vendor)';
COMMENT ON COLUMN cdk_vendor_master.payment_terms IS '[I] Payment Terms';
COMMENT ON COLUMN cdk_vendor_master.ap_control_gl_account IS '[I] AP Control GL Account';
COMMENT ON COLUMN cdk_vendor_master.vendor_status IS '[U] Vendor Status (values: ACTIVE=Active vendor; HOLD=Payment hold; INACTIVE=Inactive/closed)';
COMMENT ON COLUMN cdk_vendor_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_vendor_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_vendor_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_vendor_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_vendor_master ADD CONSTRAINT fk_cdk_vendor_master_ap_control_gl_account FOREIGN KEY (ap_control_gl_account) REFERENCES cdk_gl_account_master (gl_account_number);

-- cdk_gl_account_master (gl-account-master) -- GL Account Master
-- Chart of Accounts
-- SAP analogue: SKA1 (G/L Account Master, Chart of Accounts) / SKB1 (Company Code Data)
-- grain: one row per GL account number (+ department suffix) per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_gl_account_master (
    gl_account_number varchar(6) NOT NULL,
    department_suffix varchar(2),
    sub_account_letter varchar(1),
    account_name varchar(60),
    account_type varchar(32),
    normal_balance varchar(32),
    is_control_account boolean,
    is_department_bound boolean,
    is_active boolean,
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (gl_account_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_gl_account_master.gl_account_number IS '[D] GL Account Number (base)';
COMMENT ON COLUMN cdk_gl_account_master.department_suffix IS '[D] Department Suffix';
COMMENT ON COLUMN cdk_gl_account_master.sub_account_letter IS '[D] Sub-Account Letter Suffix';
COMMENT ON COLUMN cdk_gl_account_master.account_name IS '[D] Account Name / Description';
COMMENT ON COLUMN cdk_gl_account_master.account_type IS '[D] Account Type (values: ASSET=200-series: Assets; LIAB_EQUITY=300-series: Liabilities/Equity; SALES=400-series: Sales; COGS=600-series: Cost of Goods Sold; LEASE_RENTAL_COST=700-series: Lease/Rental Cost; OTHER_INCOME_FI=800/900-series: Other Income/F&I)';
COMMENT ON COLUMN cdk_gl_account_master.normal_balance IS '[I] Normal Balance Side (values: DEBIT=Normal debit balance (assets, COGS, lease/rental cost); CREDIT=Normal credit balance (liabilities, equity, sales, other income))';
COMMENT ON COLUMN cdk_gl_account_master.is_control_account IS '[D] Reconciliation/Control Account Flag';
COMMENT ON COLUMN cdk_gl_account_master.is_department_bound IS '[I] Department-Bound Flag';
COMMENT ON COLUMN cdk_gl_account_master.is_active IS '[U] Active Flag';
COMMENT ON COLUMN cdk_gl_account_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_gl_account_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_gl_account_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_gl_account_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_accounting_schedule (accounting-schedule) -- Accounting Schedule (Open-Item Subledger)
-- Schedule
-- SAP analogue: Reconciliation account open-item subledger (FBL3N / open items behind SKB1-XMITKZ accounts)
-- grain: one row per open item per schedule per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_accounting_schedule (
    schedule_id varchar(32),
    gl_account_number varchar(10) NOT NULL,
    control_key_type varchar(32) NOT NULL,
    control_key_value varchar(32) NOT NULL,
    open_item_amount numeric(13,2) NOT NULL,
    aging_bucket varchar(32),
    posting_date date NOT NULL,
    schedule_type varchar(32) NOT NULL,
    schedule_index_legacy varchar(32),
    is_closed boolean,
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (schedule_id)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on schedule_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_accounting_schedule.schedule_id IS '[I] Schedule ID';
COMMENT ON COLUMN cdk_accounting_schedule.gl_account_number IS '[D] Controlling GL Account';
COMMENT ON COLUMN cdk_accounting_schedule.control_key_type IS '[D] Control Key Type (values: RO_NUMBER=Repair order number; CLAIM_NUMBER=Warranty claim number; STOCK_NUMBER=Vehicle stock number; VIN_LAST8=Last 8 characters of VIN; CUSTOMER_ID=Customer ID; DEAL_CONTRACT_NUMBER=Deal/contract reference number; REFERENCE_DOC_NUMBER=General reference/document number)';
COMMENT ON COLUMN cdk_accounting_schedule.control_key_value IS '[D] Control Key Value';
COMMENT ON COLUMN cdk_accounting_schedule.open_item_amount IS '[D] Open Item Amount';
COMMENT ON COLUMN cdk_accounting_schedule.aging_bucket IS '[D] Aging Bucket (values: CURRENT=0-29 days; 30=30-59 days; 60=60-89 days; 90=90-119 days; 120_PLUS=120+ days)';
COMMENT ON COLUMN cdk_accounting_schedule.posting_date IS '[D] Posting Date';
COMMENT ON COLUMN cdk_accounting_schedule.schedule_type IS '[D] Schedule Type (values: WARRANTY_CLAIMS_RECEIVABLE=Warranty claims receivable (GL 263); NEW_VEHICLE_FLOOR_PLAN=New vehicle floor plan (GL 231 asset / 310 liability); FACTORY_RECEIVABLES=Factory receivables (GL 261); CONTRACTS_IN_TRANSIT=Contracts in transit (GL 205); SERVICE_PARTS_WIP=Service/parts work-in-process (GL 247))';
COMMENT ON COLUMN cdk_accounting_schedule.schedule_index_legacy IS '[U] Legacy Schedule Index (cross-DMS) (values: 0=No Schedule; 1=Vehicle Inventory; 2=Accounts Receivable; 3=Accounts Payable; 4=Misc Balance Forward; 5=Misc Detail Forward; 6=Combination)';
COMMENT ON COLUMN cdk_accounting_schedule.is_closed IS '[I] Item Closed/Cleared Flag';
COMMENT ON COLUMN cdk_accounting_schedule._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_accounting_schedule._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_accounting_schedule._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_accounting_schedule._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_accounting_schedule ADD CONSTRAINT fk_cdk_accounting_schedule_gl_account_number FOREIGN KEY (gl_account_number) REFERENCES cdk_gl_account_master (gl_account_number);

-- cdk_gl_journal_posting (gl-journal-posting) -- GL Journal Posting
-- Journal Entry
-- SAP analogue: BKPF (Accounting Document Header) / BSEG (Accounting Document Segment)
-- grain: one row per journal line per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_gl_journal_posting (
    document_number varchar(20),
    journal_number varchar(20),
    journal_type varchar(32) NOT NULL,
    gl_account_number varchar(10),
    schedule_field varchar(32),
    adjust_to_gl_account varchar(10),
    posting_date date,
    debit_amount numeric(13,2),
    credit_amount numeric(13,2),
    wip_endpoint_used varchar(32),
    source_module varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (document_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on document_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on gl_account_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on posting_date: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_gl_journal_posting.document_number IS '[I] Document Number';
COMMENT ON COLUMN cdk_gl_journal_posting.journal_number IS '[I] Journal Number';
COMMENT ON COLUMN cdk_gl_journal_posting.journal_type IS '[D] Journal Type (values: STANDARD_ENTRIES=Standard Entries Journal; CASH_RECEIPTS=Cash Receipts Journal; CASH_DISBURSEMENTS=Cash Disbursements Journal; PURCHASE=Purchase Journal; PAYROLL=Payroll Journal; NEW_VEHICLE_SALES_PURCHASE=New Vehicle Sales/Purchase Journal; USED_CAR_SALES=Used Car Sales Journal; INTERNAL_SALES=Internal Sales Journal; SERVICE_SALES_CASH=Service Sales (Cash) Journal; SERVICE_SALES_CHARGE=Service Sales (Charge) Journal; WARRANTY_SALES=Warranty Sales Journal; PARTS_SALES_CASH=Parts Sales (Cash) Journal; PARTS_SALES_CHARGE=Parts Sales (Charge) Journal; DEALER_EXCHANGE=Dealer Exchange Journal; STATISTICAL_DATA=Statistical Data Journal; GENERAL_JOURNAL_ENTRY=General Journal Entry)';
COMMENT ON COLUMN cdk_gl_journal_posting.gl_account_number IS '[I] GL Account Number';
COMMENT ON COLUMN cdk_gl_journal_posting.schedule_field IS '[I] Schedule Field / Control Reference';
COMMENT ON COLUMN cdk_gl_journal_posting.adjust_to_gl_account IS '[I] Adjust-To GL Account';
COMMENT ON COLUMN cdk_gl_journal_posting.posting_date IS '[I] Posting Date';
COMMENT ON COLUMN cdk_gl_journal_posting.debit_amount IS '[I] Debit Amount';
COMMENT ON COLUMN cdk_gl_journal_posting.credit_amount IS '[I] Credit Amount';
COMMENT ON COLUMN cdk_gl_journal_posting.wip_endpoint_used IS '[D] WIP Posting Endpoint (values: GL_WIP_POST=cdk/drive/glwippost/startWIP — CDK Drive Post Accounts GL WIP; GL_POST=cdk/drive/glpost/startWIP — CDK Drive Post Accounting GL)';
COMMENT ON COLUMN cdk_gl_journal_posting.source_module IS '[I] Source Module (values: SERVICE=Service (RO close); PARTS=Parts; FI=F&I / Vehicle Sale; AP=Accounts Payable; AR=Accounts Receivable; PAYROLL=Payroll)';
COMMENT ON COLUMN cdk_gl_journal_posting._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_gl_journal_posting._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_gl_journal_posting._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_gl_journal_posting._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_gl_journal_posting ADD CONSTRAINT fk_cdk_gl_journal_posting_gl_account_number FOREIGN KEY (gl_account_number) REFERENCES cdk_gl_account_master (gl_account_number);
ALTER TABLE cdk_gl_journal_posting ADD CONSTRAINT fk_cdk_gl_journal_posting_schedule_field FOREIGN KEY (schedule_field) REFERENCES cdk_accounting_schedule (control_key_value);
ALTER TABLE cdk_gl_journal_posting ADD CONSTRAINT fk_cdk_gl_journal_posting_adjust_to_gl_account FOREIGN KEY (adjust_to_gl_account) REFERENCES cdk_gl_account_master (gl_account_number);

-- cdk_repair_order (repair-order) -- Repair Order
-- Repair Order (RO)
-- SAP analogue: AUFK (Order Master) / CO Internal Order — closest SAP analogue for a service work order
-- grain: one row per repair order per rooftop
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_repair_order (
    ro_number varchar(20) NOT NULL,
    host_item_id varchar(32),
    status_code varchar(10) NOT NULL,
    status_desc varchar(40) NOT NULL,
    ro_lifecycle_state varchar(32) NOT NULL,
    has_cust_pay_flag boolean NOT NULL,
    has_int_pay_flag boolean NOT NULL,
    has_warr_pay_flag boolean NOT NULL,
    service_advisor_number bigint,
    cashier_id varchar(10),
    booker_number bigint,
    customer_id varchar(32),
    customer_name1 varchar(80),
    customer_address_line1 varchar(60),
    customer_phone_type varchar(32),
    vehicle_vin varchar(17),
    vehicle_id varchar(32),
    mileage_in numeric(13,3),
    mileage_out numeric(13,3),
    mileage_last_visit numeric(13,3),
    tag_number varchar(7),
    open_date date NOT NULL,
    open_time text,
    closed_date date,
    posted_date date,
    voided_date date,
    booked_date date,
    booked_time text,
    appointment_date date,
    appointment_time text,
    originated_from_appointment boolean,
    appointment_id bigint,
    promised_date date,
    promised_time text,
    original_promised_date date,
    original_promised_time text,
    estimated_completion_date date,
    estimated_completion_time text,
    last_service_date date,
    add_on_flag boolean,
    comeback_flag boolean,
    rental_flag boolean,
    is_customer_waiting boolean,
    is_orig_waiter boolean,
    is_sold_by_dealer boolean,
    is_special_customer boolean,
    block_auto_msg boolean,
    comments varchar(255),
    remarks varchar(255),
    contact_email_address varchar(120),
    contact_phone_number varchar(20),
    purchase_order_number varchar(20),
    priority_value bigint,
    pay_balance_due numeric(13,2),
    pay_cp_total numeric(13,2),
    total_payment_made numeric(13,2),
    payment_type_code varchar(10),
    payment_by_insurance_flag boolean,
    payment_amount numeric(13,2),
    pay_type_code varchar(32) NOT NULL,
    ro_total_sale numeric(13,2) NOT NULL,
    ro_total_cost numeric(13,2) NOT NULL,
    ro_total_tax numeric(13,2),
    ro_sale_post_deductible numeric(13,2),
    total_labor_sale numeric(13,2),
    total_parts_sale numeric(13,2),
    total_sublet_sale numeric(13,2),
    receivable_routing_target varchar(32),
    deductible_actual_amount numeric(13,2),
    deductible_maximum_amount numeric(13,2),
    mls_sublet_cost numeric(13,2),
    mls_sublet_price numeric(13,2),
    mls_lube_cost numeric(13,2),
    mls_op_code varchar(10),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (ro_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_repair_order.ro_number IS '[D] Repair Order Number';
COMMENT ON COLUMN cdk_repair_order.host_item_id IS '[D] Host Item ID';
COMMENT ON COLUMN cdk_repair_order.status_code IS '[D] Status Code';
COMMENT ON COLUMN cdk_repair_order.status_desc IS '[D] Status Description';
COMMENT ON COLUMN cdk_repair_order.ro_lifecycle_state IS '[D] RO Lifecycle State (derived) (values: OPEN=Open (getOpenRepairOrdersBulk / /open — last 31 days); WIP=Work-in-process (getWIPRepairOrders / /wip — opened, voided, or closed in the past 48 hours); CLOSED=Closed (getClosedRepairOrdersBulk / /closed — last 31 days); VOIDED=Voided (voidedDate populated))';
COMMENT ON COLUMN cdk_repair_order.has_cust_pay_flag IS '[D] Has Customer Pay Flag';
COMMENT ON COLUMN cdk_repair_order.has_int_pay_flag IS '[D] Has Internal Pay Flag';
COMMENT ON COLUMN cdk_repair_order.has_warr_pay_flag IS '[D] Has Warranty Pay Flag';
COMMENT ON COLUMN cdk_repair_order.service_advisor_number IS '[D] Service Advisor Number';
COMMENT ON COLUMN cdk_repair_order.cashier_id IS '[D] Cashier ID';
COMMENT ON COLUMN cdk_repair_order.booker_number IS '[D] Booker Number';
COMMENT ON COLUMN cdk_repair_order.customer_id IS '[D] Customer ID';
COMMENT ON COLUMN cdk_repair_order.customer_name1 IS '[D] Customer Name (embedded)';
COMMENT ON COLUMN cdk_repair_order.customer_address_line1 IS '[D] Customer Address (embedded)';
COMMENT ON COLUMN cdk_repair_order.customer_phone_type IS '[D] Customer Phone Type (embedded) (values: MAIN=Main; HOME=Home; HOME FAX=Home Fax; BUSINESS=Business; BUSINESS FAX=Business Fax; CELLULULAR=Cellular (spec's spelling); PAGER=Pager; CONTACT=Contact)';
COMMENT ON COLUMN cdk_repair_order.vehicle_vin IS '[D] Vehicle VIN (embedded)';
COMMENT ON COLUMN cdk_repair_order.vehicle_id IS '[D] Vehicle ID (embedded)';
COMMENT ON COLUMN cdk_repair_order.mileage_in IS '[D] Mileage In';
COMMENT ON COLUMN cdk_repair_order.mileage_out IS '[D] Mileage Out';
COMMENT ON COLUMN cdk_repair_order.mileage_last_visit IS '[D] Mileage At Last Visit';
COMMENT ON COLUMN cdk_repair_order.tag_number IS '[D] Tag Number';
COMMENT ON COLUMN cdk_repair_order.open_date IS '[D] Open Date';
COMMENT ON COLUMN cdk_repair_order.open_time IS '[D] Open Time';
COMMENT ON COLUMN cdk_repair_order.closed_date IS '[D] Closed Date';
COMMENT ON COLUMN cdk_repair_order.posted_date IS '[D] Posted To Accounting Date';
COMMENT ON COLUMN cdk_repair_order.voided_date IS '[D] Voided Date';
COMMENT ON COLUMN cdk_repair_order.booked_date IS '[D] Booked Date';
COMMENT ON COLUMN cdk_repair_order.booked_time IS '[D] Booked Time';
COMMENT ON COLUMN cdk_repair_order.appointment_date IS '[D] Appointment Date';
COMMENT ON COLUMN cdk_repair_order.appointment_time IS '[D] Appointment Time';
COMMENT ON COLUMN cdk_repair_order.originated_from_appointment IS '[D] Originated From Appointment Flag';
COMMENT ON COLUMN cdk_repair_order.appointment_id IS '[D] Appointment ID';
COMMENT ON COLUMN cdk_repair_order.promised_date IS '[D] Promised Date';
COMMENT ON COLUMN cdk_repair_order.promised_time IS '[D] Promised Time';
COMMENT ON COLUMN cdk_repair_order.original_promised_date IS '[D] Original Promised Date';
COMMENT ON COLUMN cdk_repair_order.original_promised_time IS '[D] Original Promised Time';
COMMENT ON COLUMN cdk_repair_order.estimated_completion_date IS '[D] Estimated Completion Date';
COMMENT ON COLUMN cdk_repair_order.estimated_completion_time IS '[D] Estimated Completion Time';
COMMENT ON COLUMN cdk_repair_order.last_service_date IS '[D] Last Service Date';
COMMENT ON COLUMN cdk_repair_order.add_on_flag IS '[D] Add-On Service Flag';
COMMENT ON COLUMN cdk_repair_order.comeback_flag IS '[D] Comeback (Return RO) Flag';
COMMENT ON COLUMN cdk_repair_order.rental_flag IS '[D] Rental Vehicle Flag';
COMMENT ON COLUMN cdk_repair_order.is_customer_waiting IS '[D] Customer Waiting Flag';
COMMENT ON COLUMN cdk_repair_order.is_orig_waiter IS '[D] Original Waiter Flag';
COMMENT ON COLUMN cdk_repair_order.is_sold_by_dealer IS '[D] Vehicle Sold By Dealer Flag';
COMMENT ON COLUMN cdk_repair_order.is_special_customer IS '[D] Special Customer Flag';
COMMENT ON COLUMN cdk_repair_order.block_auto_msg IS '[D] Block Automated Messages Flag';
COMMENT ON COLUMN cdk_repair_order.comments IS '[D] Comments';
COMMENT ON COLUMN cdk_repair_order.remarks IS '[D] Remarks';
COMMENT ON COLUMN cdk_repair_order.contact_email_address IS '[D] Contact Email (write-up)';
COMMENT ON COLUMN cdk_repair_order.contact_phone_number IS '[D] Contact Phone (write-up)';
COMMENT ON COLUMN cdk_repair_order.purchase_order_number IS '[D] Purchase Order Number';
COMMENT ON COLUMN cdk_repair_order.priority_value IS '[D] Dispatch Priority Value';
COMMENT ON COLUMN cdk_repair_order.pay_balance_due IS '[D] Payment Balance Due';
COMMENT ON COLUMN cdk_repair_order.pay_cp_total IS '[D] Customer Pay Total';
COMMENT ON COLUMN cdk_repair_order.total_payment_made IS '[D] Total Payment Made';
COMMENT ON COLUMN cdk_repair_order.payment_type_code IS '[D] Payment Type Code';
COMMENT ON COLUMN cdk_repair_order.payment_by_insurance_flag IS '[D] Payment By Insurance Flag';
COMMENT ON COLUMN cdk_repair_order.payment_amount IS '[D] Payment Amount';
COMMENT ON COLUMN cdk_repair_order.pay_type_code IS '[D] Pay Type Code (values: CP*/SR*=Customer pay / service retail; W*/SW*=Warranty (generic); WCM=Warranty — Cummins; WNA=Warranty — Navistar; I*/SI*=Internal (generic); ICV=Internal — company vehicle; IDU=Internal — demo unit; IGP=Internal — goodwill policy; IPW=Internal — parts warranty/shop supplies; IUB=Internal — trade bus/used-unit work)';
COMMENT ON COLUMN cdk_repair_order.ro_total_sale IS '[D] RO Total Sale';
COMMENT ON COLUMN cdk_repair_order.ro_total_cost IS '[D] RO Total Cost';
COMMENT ON COLUMN cdk_repair_order.ro_total_tax IS '[D] RO Total Tax';
COMMENT ON COLUMN cdk_repair_order.ro_sale_post_deductible IS '[D] RO Sale Post-Deductible';
COMMENT ON COLUMN cdk_repair_order.total_labor_sale IS '[D] Total Labor Sale';
COMMENT ON COLUMN cdk_repair_order.total_parts_sale IS '[D] Total Parts Sale';
COMMENT ON COLUMN cdk_repair_order.total_sublet_sale IS '[D] Total Sublet Sale';
COMMENT ON COLUMN cdk_repair_order.receivable_routing_target IS '[D] Receivable Routing Target (derived) (values: ANY_CUSTOMER_ACCOUNT=Customer pay routes to the specific customer's AR account; &WARCMN=Warranty (Cummins) receivable control account; &WARNAV=Warranty (Navistar) receivable control account; &100SPA / 101SPA=Internal service policy control account; &CVNEW=Internal company-vehicle control account; &NBPOL=Internal goodwill/no-charge policy control account)';
COMMENT ON COLUMN cdk_repair_order.deductible_actual_amount IS '[D] Deductible Actual Amount';
COMMENT ON COLUMN cdk_repair_order.deductible_maximum_amount IS '[D] Deductible Maximum Amount';
COMMENT ON COLUMN cdk_repair_order.mls_sublet_cost IS '[D] MLS Sublet Cost';
COMMENT ON COLUMN cdk_repair_order.mls_sublet_price IS '[D] MLS Sublet Sale Price';
COMMENT ON COLUMN cdk_repair_order.mls_lube_cost IS '[D] MLS Lube (GOG) Cost';
COMMENT ON COLUMN cdk_repair_order.mls_op_code IS '[D] MLS Operation Code';
COMMENT ON COLUMN cdk_repair_order._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_repair_order._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_repair_order._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_repair_order._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_repair_order ADD CONSTRAINT fk_cdk_repair_order_service_advisor_number FOREIGN KEY (service_advisor_number) REFERENCES cdk_employee_master (service_advisor_number);
ALTER TABLE cdk_repair_order ADD CONSTRAINT fk_cdk_repair_order_cashier_id FOREIGN KEY (cashier_id) REFERENCES cdk_employee_master (cashier_id);
ALTER TABLE cdk_repair_order ADD CONSTRAINT fk_cdk_repair_order_booker_number FOREIGN KEY (booker_number) REFERENCES cdk_employee_master (booker_number);
ALTER TABLE cdk_repair_order ADD CONSTRAINT fk_cdk_repair_order_customer_id FOREIGN KEY (customer_id) REFERENCES cdk_customer_master (customer_id);
ALTER TABLE cdk_repair_order ADD CONSTRAINT fk_cdk_repair_order_vehicle_vin FOREIGN KEY (vehicle_vin) REFERENCES cdk_vehicle_master (vin);
ALTER TABLE cdk_repair_order ADD CONSTRAINT fk_cdk_repair_order_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES cdk_vehicle_master (vehicle_id);

-- cdk_ro_labour_line (ro-labour-line) -- Repair Order Labour Line
-- RO Labor Line
-- SAP analogue: AFVC (Operation within an Order) / CATSDB (time confirmation)
-- grain: one row per labor operation per repair order
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_ro_labour_line (
    ro_number varchar(12) NOT NULL,
    line_code varchar(6) NOT NULL,
    line_status_code varchar(10),
    line_status_desc varchar(40),
    complaint_code varchar(10),
    cause varchar(255),
    service_request_text varchar(255),
    dispatch_code varchar(10),
    campaign_code varchar(10),
    line_comeback_flag boolean,
    line_add_on_flag boolean,
    actual_work_hours numeric(9,3),
    estimated_duration_hours numeric(9,3),
    story_text varchar(1000),
    story_sequence_number bigint,
    labor_op_sequence_number bigint NOT NULL,
    labor_op_code varchar(10) NOT NULL,
    labor_op_desc varchar(80),
    labor_type_code varchar(6),
    technician_ids varchar(40),
    sold_hours numeric(9,3),
    actual_hours numeric(9,3),
    flag_hours numeric(9,3),
    time_card_hours numeric(9,3),
    other_hours numeric(9,3),
    labor_sale_amount numeric(13,2),
    labor_cost_amount numeric(13,2),
    forced_shop_charge numeric(13,2),
    mcd_percentage numeric(7,4),
    labor_op_comeback_flag boolean,
    comeback_original_ro_number varchar(20),
    labor_op_booked_date date,
    hour_type_code varchar(6),
    hours_labor_type varchar(6),
    hours_percentage numeric(7,4),
    fee_type_code varchar(32),
    fee_sale_amount numeric(13,2),
    line_warranty_claim_type varchar(10),
    line_warranty_auth_code varchar(20),
    line_warranty_failed_part_no varchar(20),
    effective_labor_rate_kpi numeric(13,2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (ro_number, line_code, labor_op_sequence_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_ro_labour_line.ro_number IS '[D] the RO number this job belongs to';
COMMENT ON COLUMN cdk_ro_labour_line.line_code IS '[D] Repair Line Code';
COMMENT ON COLUMN cdk_ro_labour_line.line_status_code IS '[D] Line Status Code';
COMMENT ON COLUMN cdk_ro_labour_line.line_status_desc IS '[D] Line Status Description';
COMMENT ON COLUMN cdk_ro_labour_line.complaint_code IS '[D] Complaint Code';
COMMENT ON COLUMN cdk_ro_labour_line.cause IS '[D] Cause';
COMMENT ON COLUMN cdk_ro_labour_line.service_request_text IS '[D] Service Request Text';
COMMENT ON COLUMN cdk_ro_labour_line.dispatch_code IS '[D] Dispatch Code';
COMMENT ON COLUMN cdk_ro_labour_line.campaign_code IS '[D] Campaign Code';
COMMENT ON COLUMN cdk_ro_labour_line.line_comeback_flag IS '[D] Line Comeback Flag';
COMMENT ON COLUMN cdk_ro_labour_line.line_add_on_flag IS '[D] Line Add-On Flag';
COMMENT ON COLUMN cdk_ro_labour_line.actual_work_hours IS '[D] Actual Work Hours';
COMMENT ON COLUMN cdk_ro_labour_line.estimated_duration_hours IS '[D] Estimated Duration';
COMMENT ON COLUMN cdk_ro_labour_line.story_text IS '[D] Technician Story Text';
COMMENT ON COLUMN cdk_ro_labour_line.story_sequence_number IS '[D] Story Sequence Number';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_sequence_number IS '[D] Labor Operation Sequence Number';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_code IS '[D] Labor Operation Code';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_desc IS '[D] Labor Operation Description';
COMMENT ON COLUMN cdk_ro_labour_line.labor_type_code IS '[D] Labor Type Code';
COMMENT ON COLUMN cdk_ro_labour_line.technician_ids IS '[D] Technician ID(s)';
COMMENT ON COLUMN cdk_ro_labour_line.sold_hours IS '[D] Sold Hours';
COMMENT ON COLUMN cdk_ro_labour_line.actual_hours IS '[D] Actual Hours';
COMMENT ON COLUMN cdk_ro_labour_line.flag_hours IS '[D] Flagged Hours';
COMMENT ON COLUMN cdk_ro_labour_line.time_card_hours IS '[D] Time Card Hours';
COMMENT ON COLUMN cdk_ro_labour_line.other_hours IS '[D] Other Hours';
COMMENT ON COLUMN cdk_ro_labour_line.labor_sale_amount IS '[D] Labor Sale Amount';
COMMENT ON COLUMN cdk_ro_labour_line.labor_cost_amount IS '[D] Labor Cost Amount';
COMMENT ON COLUMN cdk_ro_labour_line.forced_shop_charge IS '[D] Forced Shop Charge';
COMMENT ON COLUMN cdk_ro_labour_line.mcd_percentage IS '[D] Split-Op MCD Percentage';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_comeback_flag IS '[D] Labor Op Comeback Flag';
COMMENT ON COLUMN cdk_ro_labour_line.comeback_original_ro_number IS '[D] Comeback Original RO Number';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_booked_date IS '[D] Labor Op Booked Date';
COMMENT ON COLUMN cdk_ro_labour_line.hour_type_code IS '[D] Hour Type Code';
COMMENT ON COLUMN cdk_ro_labour_line.hours_labor_type IS '[D] Hours-Detail Labor Type';
COMMENT ON COLUMN cdk_ro_labour_line.hours_percentage IS '[D] Technician Actual-Hours Percentage';
COMMENT ON COLUMN cdk_ro_labour_line.fee_type_code IS '[D] Fee Type Code (values: L=Lube; M=Miscellaneous; S=Sublet)';
COMMENT ON COLUMN cdk_ro_labour_line.fee_sale_amount IS '[D] Fee Sale Amount';
COMMENT ON COLUMN cdk_ro_labour_line.line_warranty_claim_type IS '[D] Warranty Claim Type (line-level)';
COMMENT ON COLUMN cdk_ro_labour_line.line_warranty_auth_code IS '[D] Warranty Authorization Code (line-level)';
COMMENT ON COLUMN cdk_ro_labour_line.line_warranty_failed_part_no IS '[D] Failed Part Number (line-level)';
COMMENT ON COLUMN cdk_ro_labour_line.effective_labor_rate_kpi IS '[I] Effective Labor Rate (derived KPI)';
COMMENT ON COLUMN cdk_ro_labour_line._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_ro_labour_line._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_ro_labour_line._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_ro_labour_line._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_technician_ids FOREIGN KEY (technician_ids) REFERENCES cdk_employee_master (technician_ids);
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_comeback_original_ro_number FOREIGN KEY (comeback_original_ro_number) REFERENCES cdk_repair_order (ro_number);
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_line_warranty_claim_type FOREIGN KEY (line_warranty_claim_type) REFERENCES cdk_warranty_claim (claim_type);
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_line_warranty_failed_part_no FOREIGN KEY (line_warranty_failed_part_no) REFERENCES cdk_parts_master_inventory (part_number);

-- cdk_ro_part_line (ro-part-line) -- Repair Order Part Line
-- RO Parts Line
-- SAP analogue: MSEG (Material Document Segment) / RESB (Reservation)
-- grain: one row per part line per labor operation per repair order
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_ro_part_line (
    ro_number varchar(12) NOT NULL,
    part_sequence_number bigint NOT NULL,
    part_number varchar(20) NOT NULL,
    part_description varchar(60),
    bin1_location varchar(10),
    part_source_number varchar(10),
    parts_class_code varchar(10),
    associated_labor_sequence_number bigint,
    part_labor_type varchar(6),
    part_line_code varchar(6) NOT NULL,
    escalated_unit_cost numeric(13,2),
    escalated_unit_list_price numeric(13,2),
    escalated_unit_sale_price numeric(13,2),
    extended_cost numeric(13,2),
    extended_sale numeric(13,2),
    core_cost numeric(13,2),
    core_sale numeric(13,2),
    unit_service_charge numeric(13,2),
    part_mcd_percentage numeric(7,4),
    unit_comp_price numeric(13,2),
    comp_line_code varchar(6),
    quantity_sold numeric(13,3),
    quantity_ordered numeric(13,3),
    quantity_filled numeric(13,3),
    quantity_backordered numeric(13,3),
    quantity_on_hand_at_sale numeric(13,3),
    part_special_status varchar(10),
    counter_person_employee_id bigint,
    outside_salesman_id bigint,
    part_fee_type_code varchar(32),
    fee_lop_or_part_flag varchar(32),
    transaction_code varchar(32),
    star_part_type_code varchar(32),
    hazmat_indicator boolean,
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (ro_number, part_sequence_number, part_line_code)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_ro_part_line.ro_number IS '[D] the RO number this part was sold on';
COMMENT ON COLUMN cdk_ro_part_line.part_sequence_number IS '[D] Part Sequence Number';
COMMENT ON COLUMN cdk_ro_part_line.part_number IS '[D] Part Number';
COMMENT ON COLUMN cdk_ro_part_line.part_description IS '[D] Part Description';
COMMENT ON COLUMN cdk_ro_part_line.bin1_location IS '[D] Main Bin Location';
COMMENT ON COLUMN cdk_ro_part_line.part_source_number IS '[D] Part Source Number';
COMMENT ON COLUMN cdk_ro_part_line.parts_class_code IS '[D] Parts Class Code';
COMMENT ON COLUMN cdk_ro_part_line.associated_labor_sequence_number IS '[D] Associated Labor Sequence Number';
COMMENT ON COLUMN cdk_ro_part_line.part_labor_type IS '[D] Part Labor Type';
COMMENT ON COLUMN cdk_ro_part_line.part_line_code IS '[D] Part Repair Line Code';
COMMENT ON COLUMN cdk_ro_part_line.escalated_unit_cost IS '[D] Escalated Unit Cost';
COMMENT ON COLUMN cdk_ro_part_line.escalated_unit_list_price IS '[D] Escalated Unit List Price';
COMMENT ON COLUMN cdk_ro_part_line.escalated_unit_sale_price IS '[D] Escalated Unit Sale Price';
COMMENT ON COLUMN cdk_ro_part_line.extended_cost IS '[D] Extended Cost';
COMMENT ON COLUMN cdk_ro_part_line.extended_sale IS '[D] Extended Sale';
COMMENT ON COLUMN cdk_ro_part_line.core_cost IS '[D] Core Cost';
COMMENT ON COLUMN cdk_ro_part_line.core_sale IS '[D] Core Sale (Core Charge)';
COMMENT ON COLUMN cdk_ro_part_line.unit_service_charge IS '[D] Unit Service Charge (returns)';
COMMENT ON COLUMN cdk_ro_part_line.part_mcd_percentage IS '[D] Split-Part MCD Percentage';
COMMENT ON COLUMN cdk_ro_part_line.unit_comp_price IS '[D] Unit Comp Price';
COMMENT ON COLUMN cdk_ro_part_line.comp_line_code IS '[D] Comp Repair Line Code';
COMMENT ON COLUMN cdk_ro_part_line.quantity_sold IS '[D] Quantity Sold';
COMMENT ON COLUMN cdk_ro_part_line.quantity_ordered IS '[D] Quantity Ordered';
COMMENT ON COLUMN cdk_ro_part_line.quantity_filled IS '[D] Quantity Filled';
COMMENT ON COLUMN cdk_ro_part_line.quantity_backordered IS '[D] Quantity Backordered';
COMMENT ON COLUMN cdk_ro_part_line.quantity_on_hand_at_sale IS '[D] Quantity On Hand (at time of sale)';
COMMENT ON COLUMN cdk_ro_part_line.part_special_status IS '[D] Part Special Status';
COMMENT ON COLUMN cdk_ro_part_line.counter_person_employee_id IS '[D] Counter Person Employee ID';
COMMENT ON COLUMN cdk_ro_part_line.outside_salesman_id IS '[D] Outside Salesman ID';
COMMENT ON COLUMN cdk_ro_part_line.part_fee_type_code IS '[D] Part Fee Type Code (values: L=Lube; M=Miscellaneous; S=Sublet)';
COMMENT ON COLUMN cdk_ro_part_line.fee_lop_or_part_flag IS '[D] Fee Applies To Labor Or Part Flag (values: L=Labor; P=Part)';
COMMENT ON COLUMN cdk_ro_part_line.transaction_code IS '[D] CDK Parts Transaction Code (values: (blank)/N=Normal sale/return; W=Warranty sale; NW=Warranty return; DS=Warranty drop-ship sale; DW=Warranty drop-ship return; H=Wholesale sale; NH=Wholesale return; M=Minus adjustment; P=Plus adjustment; L=Lost sale (true lost sale))';
COMMENT ON COLUMN cdk_ro_part_line.star_part_type_code IS '[I] STAR PartTypeCode (cross-vendor) (values: H=Manufacturer Part Code; P=Part Number)';
COMMENT ON COLUMN cdk_ro_part_line.hazmat_indicator IS '[I] Hazmat Indicator (STAR analogue)';
COMMENT ON COLUMN cdk_ro_part_line._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_ro_part_line._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_ro_part_line._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_ro_part_line._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_ro_part_line ADD CONSTRAINT fk_cdk_ro_part_line_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number);
ALTER TABLE cdk_ro_part_line ADD CONSTRAINT fk_cdk_ro_part_line_associated_labor_sequence_number FOREIGN KEY (associated_labor_sequence_number) REFERENCES cdk_ro_labour_line (labor_op_sequence_number);
ALTER TABLE cdk_ro_part_line ADD CONSTRAINT fk_cdk_ro_part_line_counter_person_employee_id FOREIGN KEY (counter_person_employee_id) REFERENCES cdk_employee_master (parts_counter_employee_id);
ALTER TABLE cdk_ro_part_line ADD CONSTRAINT fk_cdk_ro_part_line_outside_salesman_id FOREIGN KEY (outside_salesman_id) REFERENCES cdk_employee_master (outside_salesman_id);

-- cdk_parts_master_inventory (parts-master-inventory) -- Parts Master / Inventory
-- Parts Inventory
-- SAP analogue: MARA (Material Master) / MARD (Storage Location Data) / MBEW (Material Valuation)
-- grain: one row per part number per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_parts_master_inventory (
    part_number varchar(20) NOT NULL,
    description varchar(60),
    manufacturer varchar(40),
    quantity_on_hand numeric(13,3),
    bin_location varchar(10),
    bin2_location varchar(10),
    unit_cost numeric(13,2),
    list_price numeric(13,2),
    last_sale_date date,
    date_received date,
    delete_part_flag boolean,
    group_code varchar(10),
    minimum_stock_level numeric(13,3),
    maximum_stock_level numeric(13,3),
    safety_stock_level numeric(13,3),
    supersession_successor_part_number varchar(20),
    part_condition_code varchar(32),
    vmrs_code varchar(10),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (part_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_parts_master_inventory.part_number IS '[D] Part Number';
COMMENT ON COLUMN cdk_parts_master_inventory.description IS '[D] Description';
COMMENT ON COLUMN cdk_parts_master_inventory.manufacturer IS '[D] Manufacturer';
COMMENT ON COLUMN cdk_parts_master_inventory.quantity_on_hand IS '[D] Quantity On Hand';
COMMENT ON COLUMN cdk_parts_master_inventory.bin_location IS '[D] Bin Location';
COMMENT ON COLUMN cdk_parts_master_inventory.bin2_location IS '[I] Alternate Bin Location';
COMMENT ON COLUMN cdk_parts_master_inventory.unit_cost IS '[D] Unit Cost';
COMMENT ON COLUMN cdk_parts_master_inventory.list_price IS '[D] List Price';
COMMENT ON COLUMN cdk_parts_master_inventory.last_sale_date IS '[D] Last Sale Date';
COMMENT ON COLUMN cdk_parts_master_inventory.date_received IS '[D] Date Received';
COMMENT ON COLUMN cdk_parts_master_inventory.delete_part_flag IS '[D] Delete Part Flag';
COMMENT ON COLUMN cdk_parts_master_inventory.group_code IS '[D] Group Code';
COMMENT ON COLUMN cdk_parts_master_inventory.minimum_stock_level IS '[D] Minimum Stock Level';
COMMENT ON COLUMN cdk_parts_master_inventory.maximum_stock_level IS '[D] Maximum Stock Level';
COMMENT ON COLUMN cdk_parts_master_inventory.safety_stock_level IS '[D] Safety Stock Level';
COMMENT ON COLUMN cdk_parts_master_inventory.supersession_successor_part_number IS '[I] Supersession Chain — Successor Part Number';
COMMENT ON COLUMN cdk_parts_master_inventory.part_condition_code IS '[I] Part Condition Code (STAR analogue) (values: NEW=New part; CORE=Core/remanufactured-eligible; REMAN=Remanufactured part)';
COMMENT ON COLUMN cdk_parts_master_inventory.vmrs_code IS '[I] VMRS Code';
COMMENT ON COLUMN cdk_parts_master_inventory._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_parts_master_inventory._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_parts_master_inventory._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_parts_master_inventory._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_parts_master_inventory ADD CONSTRAINT fk_cdk_parts_master_inventory_supersession_successor_part_number FOREIGN KEY (supersession_successor_part_number) REFERENCES cdk_parts_master_inventory (part_number);

-- cdk_parts_order_supersession (parts-order-supersession) -- Parts Order / Supersession
-- Parts Order & Supersession
-- SAP analogue: MMPUR (Purchase Order) / MARA-supersession chain (custom Z-table analogue)
-- grain: one row per parts order line, or one row per supersession chain hop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_parts_order_supersession (
    order_type varchar(32) NOT NULL,
    ordering_platform varchar(40),
    cdk_function_code varchar(32),
    order_number varchar(20),
    part_number varchar(20),
    superseded_by_part_number varchar(20),
    quantity_ordered numeric(13,3),
    order_date date,
    confirmation_status varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (order_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on order_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on part_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_parts_order_supersession.order_type IS '[D] PACCAR MDI Order Type (values: STOCK=Stock order; EMERGENCY=Emergency order; MKT=Marketing Suggestion order; COF=Auto Confirmed order)';
COMMENT ON COLUMN cdk_parts_order_supersession.ordering_platform IS '[D] Ordering Platform';
COMMENT ON COLUMN cdk_parts_order_supersession.cdk_function_code IS '[I] CDK Ordering Function Code (values: IRO=Stocking parameters; IRE=Generate suggested stock order; PO=Manual order; RMR=Report MO (Manufacturer Order) Review)';
COMMENT ON COLUMN cdk_parts_order_supersession.order_number IS '[I] Order Number';
COMMENT ON COLUMN cdk_parts_order_supersession.part_number IS '[I] Part Number';
COMMENT ON COLUMN cdk_parts_order_supersession.superseded_by_part_number IS '[I] Superseded-By Part Number';
COMMENT ON COLUMN cdk_parts_order_supersession.quantity_ordered IS '[I] Quantity Ordered';
COMMENT ON COLUMN cdk_parts_order_supersession.order_date IS '[I] Order Date';
COMMENT ON COLUMN cdk_parts_order_supersession.confirmation_status IS '[I] Confirmation Status (values: PENDING=Pending confirmation; CONFIRMED=Confirmed; REJECTED=Rejected)';
COMMENT ON COLUMN cdk_parts_order_supersession._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_parts_order_supersession._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_parts_order_supersession._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_parts_order_supersession._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_parts_order_supersession ADD CONSTRAINT fk_cdk_parts_order_supersession_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number);
ALTER TABLE cdk_parts_order_supersession ADD CONSTRAINT fk_cdk_parts_order_supersession_superseded_by_part_number FOREIGN KEY (superseded_by_part_number) REFERENCES cdk_parts_master_inventory (part_number);

-- cdk_parts_pick_ticket (parts-pick-ticket) -- Parts Pick Ticket
-- Parts Pick Ticket
-- SAP analogue: Transfer Order / Reservation withdrawal document (LB03/MB1B analogue)
-- grain: one row per pick-ticket line
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_parts_pick_ticket (
    pick_ticket_id varchar(20) NOT NULL,
    ro_number varchar(20),
    counter_sale_id varchar(20),
    part_number varchar(20),
    quantity_picked numeric(13,3),
    pick_bin_location varchar(10),
    picked_by_employee_id varchar(10),
    pick_date date,
    pick_status varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (pick_ticket_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_parts_pick_ticket.pick_ticket_id IS '[D] Pick Ticket ID';
COMMENT ON COLUMN cdk_parts_pick_ticket.ro_number IS '[I] Associated RO Number';
COMMENT ON COLUMN cdk_parts_pick_ticket.counter_sale_id IS '[I] Associated Counter Sale ID';
COMMENT ON COLUMN cdk_parts_pick_ticket.part_number IS '[I] Part Number';
COMMENT ON COLUMN cdk_parts_pick_ticket.quantity_picked IS '[I] Quantity Picked';
COMMENT ON COLUMN cdk_parts_pick_ticket.pick_bin_location IS '[I] Pick Bin Location';
COMMENT ON COLUMN cdk_parts_pick_ticket.picked_by_employee_id IS '[I] Picked-By Employee ID';
COMMENT ON COLUMN cdk_parts_pick_ticket.pick_date IS '[I] Pick Date';
COMMENT ON COLUMN cdk_parts_pick_ticket.pick_status IS '[I] Pick Status (values: OPEN=Not yet picked; PICKED=Picked, awaiting issue; ISSUED=Issued to RO/counter sale)';
COMMENT ON COLUMN cdk_parts_pick_ticket._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_parts_pick_ticket._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_parts_pick_ticket._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_parts_pick_ticket._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_parts_pick_ticket ADD CONSTRAINT fk_cdk_parts_pick_ticket_ro_number FOREIGN KEY (ro_number) REFERENCES cdk_repair_order (ro_number);
ALTER TABLE cdk_parts_pick_ticket ADD CONSTRAINT fk_cdk_parts_pick_ticket_counter_sale_id FOREIGN KEY (counter_sale_id) REFERENCES cdk_counter_parts_sale (counter_sale_id);
ALTER TABLE cdk_parts_pick_ticket ADD CONSTRAINT fk_cdk_parts_pick_ticket_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number);
ALTER TABLE cdk_parts_pick_ticket ADD CONSTRAINT fk_cdk_parts_pick_ticket_picked_by_employee_id FOREIGN KEY (picked_by_employee_id) REFERENCES cdk_employee_master (service_advisor_number);

-- cdk_counter_parts_sale (counter-parts-sale) -- Counter Parts Sale
-- Parts Counter/Special Order Sale
-- SAP analogue: VBRK/VBRP (Billing Document Header/Item) for a stand-alone parts sale
-- grain: one row per counter-sale line
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_counter_parts_sale (
    counter_sale_id varchar(20) NOT NULL,
    sale_status varchar(32) NOT NULL,
    customer_id varchar(32),
    part_number varchar(20),
    quantity_sold numeric(13,3),
    unit_sale_price numeric(13,2),
    sale_date date,
    transaction_code varchar(32),
    invoice_number varchar(20),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (counter_sale_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_counter_parts_sale.counter_sale_id IS '[D] Counter Sale ID';
COMMENT ON COLUMN cdk_counter_parts_sale.sale_status IS '[D] Sale Status (values: OPEN=Allocated/reserved, not yet invoiced (Async Open Parts Sales); CLOSED=Invoiced and posted (Async Closed Parts Sales))';
COMMENT ON COLUMN cdk_counter_parts_sale.customer_id IS '[U] Customer ID';
COMMENT ON COLUMN cdk_counter_parts_sale.part_number IS '[U] Part Number';
COMMENT ON COLUMN cdk_counter_parts_sale.quantity_sold IS '[U] Quantity Sold';
COMMENT ON COLUMN cdk_counter_parts_sale.unit_sale_price IS '[U] Unit Sale Price';
COMMENT ON COLUMN cdk_counter_parts_sale.sale_date IS '[U] Sale Date';
COMMENT ON COLUMN cdk_counter_parts_sale.transaction_code IS '[D] CDK Parts Transaction Code (values: (blank)/N=Normal sale/return; W=Warranty sale; H=Wholesale sale; M=Minus adjustment; P=Plus adjustment; L=Lost sale)';
COMMENT ON COLUMN cdk_counter_parts_sale.invoice_number IS '[U] Invoice Number';
COMMENT ON COLUMN cdk_counter_parts_sale._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_counter_parts_sale._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_counter_parts_sale._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_counter_parts_sale._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_counter_parts_sale ADD CONSTRAINT fk_cdk_counter_parts_sale_customer_id FOREIGN KEY (customer_id) REFERENCES cdk_customer_master (customer_id);
ALTER TABLE cdk_counter_parts_sale ADD CONSTRAINT fk_cdk_counter_parts_sale_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number);

-- cdk_deal_jacket_vehicle_sale (deal-jacket-vehicle-sale) -- Deal Jacket / Vehicle Sale
-- Deal Jacket
-- SAP analogue: VBAK/VBAP (Sales Order) + posted Billing Document — closest SAP analogue for a vehicle sale + F&I bundle
-- grain: one row per deal per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_deal_jacket_vehicle_sale (
    deal_id varchar(20),
    deal_status varchar(32),
    deal_lifecycle_stage varchar(32),
    customer_id varchar(32),
    vehicle_id varchar(32),
    sale_price numeric(13,2),
    trade_in_vehicle_id varchar(32),
    finance_source_lender_id varchar(20),
    we_owe_description varchar(120),
    deal_type varchar(32),
    fi_products_sold varchar(255),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (deal_id)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on deal_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on deal_status: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)
    -- NOT NULL withheld on deal_lifecycle_stage: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.deal_id IS '[I] Deal ID';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.deal_status IS '[U] Deal / FI Sales Status (values: C=Likely: Cancelled (unconfirmed); B=Likely: Booked (unconfirmed); P=Likely: Pending (unconfirmed); F=Likely: Finalized (unconfirmed); I=Likely: Incomplete (unconfirmed); U=Likely: Unknown/Unposted (unconfirmed))';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.deal_lifecycle_stage IS '[I] Deal Lifecycle Stage (documented chain) (values: PROSPECT=Prospect; QUOTE_DESK=Quote / Desk deal; PENDING_DEAL=Pending Deal; WE_OWE=We-Owe(s); FINALIZED_BOOKED=Finalized (Booked) Deal; POSTED=Posted Vehicle Sale + F&I schedule entries)';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.customer_id IS '[U] Customer ID';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.vehicle_id IS '[U] Vehicle ID (VIN)';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.sale_price IS '[U] Vehicle Sale Price';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.trade_in_vehicle_id IS '[U] Trade-In Vehicle ID';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.finance_source_lender_id IS '[U] Finance Source / Lender ID';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.we_owe_description IS '[I] We-Owe Item Description';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.deal_type IS '[I] Deal Type (values: CASH=Cash deal; FINANCE=Finance deal; LEASE=Lease deal)';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.fi_products_sold IS '[U] F&I Products Sold';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_deal_jacket_vehicle_sale ADD CONSTRAINT fk_cdk_deal_jacket_vehicle_sale_customer_id FOREIGN KEY (customer_id) REFERENCES cdk_customer_master (customer_id);
ALTER TABLE cdk_deal_jacket_vehicle_sale ADD CONSTRAINT fk_cdk_deal_jacket_vehicle_sale_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES cdk_vehicle_master (vehicle_id);
ALTER TABLE cdk_deal_jacket_vehicle_sale ADD CONSTRAINT fk_cdk_deal_jacket_vehicle_sale_trade_in_vehicle_id FOREIGN KEY (trade_in_vehicle_id) REFERENCES cdk_vehicle_master (vehicle_id);
ALTER TABLE cdk_deal_jacket_vehicle_sale ADD CONSTRAINT fk_cdk_deal_jacket_vehicle_sale_finance_source_lender_id FOREIGN KEY (finance_source_lender_id) REFERENCES cdk_vendor_master (vendor_id);

-- cdk_technician_time_punch (technician-time-punch) -- Technician Time Punch
-- Technician Clock Punch
-- SAP analogue: CATSDB (Time Sheet / Cross-Application Time Sheet)
-- grain: one row per technician clock punch per repair-order line per work date
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_technician_time_punch (
    technician_id bigint NOT NULL,
    line_code varchar(6) NOT NULL,
    work_date date NOT NULL,
    time_on text NOT NULL,
    time_off text,
    duration_hours numeric(9,3),
    work_type_code varchar(10),
    altered_flag boolean,
    ro_number varchar(20) NOT NULL,
    payroll_export_batch_id varchar(20),
    indirect_time_code varchar(10),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (technician_id, line_code, work_date, time_on, ro_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_technician_time_punch.technician_id IS '[D] Technician ID';
COMMENT ON COLUMN cdk_technician_time_punch.line_code IS '[D] Repair Line Code';
COMMENT ON COLUMN cdk_technician_time_punch.work_date IS '[D] Work Date';
COMMENT ON COLUMN cdk_technician_time_punch.time_on IS '[D] Time Punched On';
COMMENT ON COLUMN cdk_technician_time_punch.time_off IS '[D] Time Punched Off';
COMMENT ON COLUMN cdk_technician_time_punch.duration_hours IS '[D] Duration Hours';
COMMENT ON COLUMN cdk_technician_time_punch.work_type_code IS '[D] Work Type Code';
COMMENT ON COLUMN cdk_technician_time_punch.altered_flag IS '[D] Altered Flag';
COMMENT ON COLUMN cdk_technician_time_punch.ro_number IS '[D] Associated RO Number';
COMMENT ON COLUMN cdk_technician_time_punch.payroll_export_batch_id IS '[U] Payroll Export Batch ID';
COMMENT ON COLUMN cdk_technician_time_punch.indirect_time_code IS '[U] Indirect/Non-RO Time Code';
COMMENT ON COLUMN cdk_technician_time_punch._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_technician_time_punch._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_technician_time_punch._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_technician_time_punch._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- cdk_work_in_process (work-in-process) -- Work In Process
-- WIP Schedule
-- SAP analogue: Anlagen im Bau (AIB) suspense-account analogue / CO-PA WIP settlement (conceptual analogue only)
-- grain: one row per RO per WIP snapshot date
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_work_in_process (
    wip_snapshot_date date,
    ro_number varchar(20) NOT NULL,
    wip_status varchar(32) NOT NULL,
    wip_labor_amount numeric(13,2),
    wip_parts_amount numeric(13,2),
    wip_opened_date date,
    wip_age_days numeric(13,3),
    wip_closed_date date,
    wip_gl_account varchar(10),
    wip_department_suffix varchar(4),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (wip_snapshot_date, ro_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on wip_snapshot_date: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_work_in_process.wip_snapshot_date IS '[I] the date this work-in-process balance was captured';
COMMENT ON COLUMN cdk_work_in_process.ro_number IS '[D] Associated RO Number';
COMMENT ON COLUMN cdk_work_in_process.wip_status IS '[D] WIP Status (values: OPENED=RO opened within the WIP window (past 48h); VOIDED=RO voided within the WIP window; CLOSED=RO closed within the WIP window)';
COMMENT ON COLUMN cdk_work_in_process.wip_labor_amount IS '[I] WIP Labor Amount (suspense)';
COMMENT ON COLUMN cdk_work_in_process.wip_parts_amount IS '[I] WIP Parts Amount (suspense)';
COMMENT ON COLUMN cdk_work_in_process.wip_opened_date IS '[D] WIP Opened Date';
COMMENT ON COLUMN cdk_work_in_process.wip_age_days IS '[I] WIP Age in Days';
COMMENT ON COLUMN cdk_work_in_process.wip_closed_date IS '[D] WIP Closed Date';
COMMENT ON COLUMN cdk_work_in_process.wip_gl_account IS '[I] WIP GL Suspense Account';
COMMENT ON COLUMN cdk_work_in_process.wip_department_suffix IS '[I] WIP Department/Cost-Centre Suffix';
COMMENT ON COLUMN cdk_work_in_process._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_work_in_process._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_work_in_process._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_work_in_process._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_work_in_process ADD CONSTRAINT fk_cdk_work_in_process_wip_gl_account FOREIGN KEY (wip_gl_account) REFERENCES cdk_gl_account_master (gl_account_number);
ALTER TABLE cdk_work_in_process ADD CONSTRAINT fk_cdk_work_in_process_wip_department_suffix FOREIGN KEY (wip_department_suffix) REFERENCES cdk_cost_centre_department (department_code);

-- cdk_warranty_claim (warranty-claim) -- Warranty Claim
-- Warranty Claim
-- SAP analogue: Not a native SAP object; closest conceptual analogue is a customer/OEM debit memo tied to a service notification (IW51/IW52) with its own receivable account
-- grain: one row per warranty claim
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_warranty_claim (
    claim_number varchar(20),
    ro_number varchar(20),
    vin varchar(17),
    causal_part_number varchar(20),
    claim_category_code varchar(10),
    concern_text varchar(1000),
    cause_text varchar(1000),
    correction_text varchar(1000),
    srt_code varchar(10),
    claim_story_text varchar(1000),
    campaign_number varchar(20),
    failure_code varchar(10),
    submission_window_days numeric(13,3),
    claim_type varchar(32),
    claim_status varchar(32),
    gl_account_claim_receivable varchar(10),
    aging_bucket varchar(32),
    claim_amount numeric(13,2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (claim_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on claim_number: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)
    -- NOT NULL withheld on ro_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on vin: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_warranty_claim.claim_number IS '[U] Warranty Claim Number';
COMMENT ON COLUMN cdk_warranty_claim.ro_number IS '[I] Source RO Number';
COMMENT ON COLUMN cdk_warranty_claim.vin IS '[I] Vehicle VIN';
COMMENT ON COLUMN cdk_warranty_claim.causal_part_number IS '[I] Causal / Removed Part Number';
COMMENT ON COLUMN cdk_warranty_claim.claim_category_code IS '[I] Claim Category Code';
COMMENT ON COLUMN cdk_warranty_claim.concern_text IS '[I] Concern Narrative';
COMMENT ON COLUMN cdk_warranty_claim.cause_text IS '[I] Cause Narrative';
COMMENT ON COLUMN cdk_warranty_claim.correction_text IS '[I] Correction Narrative';
COMMENT ON COLUMN cdk_warranty_claim.srt_code IS '[I] SRT (Standard Repair Time) Code';
COMMENT ON COLUMN cdk_warranty_claim.claim_story_text IS '[I] Claim Story Text';
COMMENT ON COLUMN cdk_warranty_claim.campaign_number IS '[I] Campaign Number';
COMMENT ON COLUMN cdk_warranty_claim.failure_code IS '[I] Failure Code';
COMMENT ON COLUMN cdk_warranty_claim.submission_window_days IS '[I] Submission Window (Days)';
COMMENT ON COLUMN cdk_warranty_claim.claim_type IS '[I] Claim Type (values: QUICK=Quick Claim (pre-coded campaign/failure code); LONG=Long-form claim (manual narrative entry))';
COMMENT ON COLUMN cdk_warranty_claim.claim_status IS '[U] Claim Status (values: DRAFT=Draft (created from RO, not yet submitted); SUBMITTED=Submitted to PRWS; PAID=Factory paid; REJECTED=Factory rejected)';
COMMENT ON COLUMN cdk_warranty_claim.gl_account_claim_receivable IS '[I] GL Warranty Claims Receivable Account';
COMMENT ON COLUMN cdk_warranty_claim.aging_bucket IS '[I] Claim Aging Bucket (values: 0-30=0-30 days; 31-60=31-60 days; 61-90=61-90 days; 90+=90+ days)';
COMMENT ON COLUMN cdk_warranty_claim.claim_amount IS '[U] Claim Amount';
COMMENT ON COLUMN cdk_warranty_claim._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_warranty_claim._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_warranty_claim._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_warranty_claim._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_warranty_claim ADD CONSTRAINT fk_cdk_warranty_claim_ro_number FOREIGN KEY (ro_number) REFERENCES cdk_repair_order (ro_number);
ALTER TABLE cdk_warranty_claim ADD CONSTRAINT fk_cdk_warranty_claim_vin FOREIGN KEY (vin) REFERENCES cdk_vehicle_master (vin);
ALTER TABLE cdk_warranty_claim ADD CONSTRAINT fk_cdk_warranty_claim_causal_part_number FOREIGN KEY (causal_part_number) REFERENCES cdk_parts_master_inventory (part_number);
ALTER TABLE cdk_warranty_claim ADD CONSTRAINT fk_cdk_warranty_claim_gl_account_claim_receivable FOREIGN KEY (gl_account_claim_receivable) REFERENCES cdk_gl_account_master (gl_account_number);

-- cdk_purchase_receipt_document (purchase-receipt-document) -- Purchase / Receipt Document
-- Purchase Order & Receipt
-- SAP analogue: EKKO/EKPO (Purchase Order Header/Item) + MSEG (Material Document, Movement Type 101 Goods Receipt)
-- grain: one row per PO line receipt
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_purchase_receipt_document (
    purchase_order_number varchar(20),
    vendor_id varchar(20),
    po_date date,
    po_line_number bigint,
    part_number varchar(20),
    quantity_ordered numeric(13,3),
    quantity_received numeric(13,3),
    receipt_document_number varchar(20),
    receipt_date date,
    asn_number varchar(30),
    invoice_number varchar(20),
    unit_cost numeric(13,2),
    three_way_match_status varchar(32),
    ap_posting_gl_account varchar(10),
    movement_type_sap_analogue varchar(4),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (purchase_order_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on purchase_order_number: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)
    -- NOT NULL withheld on vendor_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on po_line_number: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_purchase_receipt_document.purchase_order_number IS '[U] Purchase Order Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.vendor_id IS '[I] Vendor ID';
COMMENT ON COLUMN cdk_purchase_receipt_document.po_date IS '[U] PO Date';
COMMENT ON COLUMN cdk_purchase_receipt_document.po_line_number IS '[U] PO Line Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.part_number IS '[I] Part Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.quantity_ordered IS '[U] Quantity Ordered';
COMMENT ON COLUMN cdk_purchase_receipt_document.quantity_received IS '[I] Quantity Received';
COMMENT ON COLUMN cdk_purchase_receipt_document.receipt_document_number IS '[U] Receipt (GR) Document Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.receipt_date IS '[I] Receipt Date';
COMMENT ON COLUMN cdk_purchase_receipt_document.asn_number IS '[I] Advance Ship Notice (ASN) Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.invoice_number IS '[I] Vendor Invoice Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.unit_cost IS '[U] Unit Cost (Invoiced)';
COMMENT ON COLUMN cdk_purchase_receipt_document.three_way_match_status IS '[I] Three-Way Match Status (values: MATCHED=PO, receipt, and invoice all agree; QTY_VARIANCE=Quantity variance between receipt and invoice; PRICE_VARIANCE=Price variance between PO and invoice; UNMATCHED=Not yet matched)';
COMMENT ON COLUMN cdk_purchase_receipt_document.ap_posting_gl_account IS '[I] AP Posting GL Account';
COMMENT ON COLUMN cdk_purchase_receipt_document.movement_type_sap_analogue IS '[I] Movement Type (SAP Analogue)';
COMMENT ON COLUMN cdk_purchase_receipt_document._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_purchase_receipt_document._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_purchase_receipt_document._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_purchase_receipt_document._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_vendor_id FOREIGN KEY (vendor_id) REFERENCES cdk_vendor_master (vendor_id);
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number);
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_invoice_number FOREIGN KEY (invoice_number) REFERENCES cdk_vendor_master (vendor_id);
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_ap_posting_gl_account FOREIGN KEY (ap_posting_gl_account) REFERENCES cdk_gl_account_master (gl_account_number);
