-- cdk_cost_centre_department (cost-centre-department) -- Cost Centre / Department
-- Department
-- SAP analogue: Cost Center (Kostenstelle) / Profit Center
-- grain: one row per department code per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_cost_centre_department (
    department_code varchar(2) NOT NULL,
    department_id varchar(32) NOT NULL,
    dms_type varchar(32) NOT NULL,
    department_name varchar(60),
    schedule_index varchar(32),
    absorption_rate_is_report_only boolean,
    cost_center_type varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (department_code)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_cost_centre_department.department_code IS '[D] Dept # (values: 01=New Vehicles; 02=Used Vehicles; 03=Lease & Rental; 04=Finance & Insurance (F&I); 05=Mechanical / Service; 06=Body Shop; 07=Parts & Accessories; 09=General & Administrative)';
COMMENT ON COLUMN cdk_cost_centre_department.department_id IS '[D] Department-Id';
COMMENT ON COLUMN cdk_cost_centre_department.dms_type IS '[D] Bound DMS Type (values: Accounting=Accounting; Finance=Finance; Inventory=Inventory; Parts=Parts; Service=Service)';
COMMENT ON COLUMN cdk_cost_centre_department.department_name IS '[I] Department Name';
COMMENT ON COLUMN cdk_cost_centre_department.schedule_index IS '[U] Schedule Index Type (values: 0=No Schedule; 1=Vehicle Inventory; 2=Accounts Receivable; 3=Accounts Payable; 4=Miscellaneous Balance Forward; 5=Miscellaneous Detail Forward; 6=Combination)';
COMMENT ON COLUMN cdk_cost_centre_department.absorption_rate_is_report_only IS '[I] Absorption Rate — Reporting Only';
COMMENT ON COLUMN cdk_cost_centre_department.cost_center_type IS '[I] Cost Center Type (values: FIXED=Fixed operations (Service/Parts/Body Shop); VARIABLE=Variable operations (New/Used vehicle sales, F&I))';
COMMENT ON COLUMN cdk_cost_centre_department._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_cost_centre_department._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_cost_centre_department._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_cost_centre_department._batch_id IS '[D] the extract run/batch identifier this row landed with';
