-- cdk_counter_parts_sale (counter-parts-sale) -- Counter Parts Sale
-- Parts Counter/Special Order Sale
-- SAP analogue: VBRK/VBRP (Billing Document Header/Item) for a stand-alone parts sale
-- grain: one row per counter-sale line
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_counter_parts_sale (
    counter_sale_id varchar(20) NOT NULL,
    sale_status varchar(32) NOT NULL,
    customer_id varchar(32),
    part_number varchar(20),
    quantity_sold numeric(13,3),
    unit_sale_price numeric(13,2),
    sale_date date,
    transaction_code varchar(32),
    invoice_number varchar(20),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (counter_sale_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_counter_parts_sale.counter_sale_id IS '[D] Counter Sale ID';
COMMENT ON COLUMN cdk_counter_parts_sale.sale_status IS '[D] Sale Status (values: OPEN=Allocated/reserved, not yet invoiced (Async Open Parts Sales); CLOSED=Invoiced and posted (Async Closed Parts Sales))';
COMMENT ON COLUMN cdk_counter_parts_sale.customer_id IS '[U] Customer ID';
COMMENT ON COLUMN cdk_counter_parts_sale.part_number IS '[U] Part Number';
COMMENT ON COLUMN cdk_counter_parts_sale.quantity_sold IS '[U] Quantity Sold';
COMMENT ON COLUMN cdk_counter_parts_sale.unit_sale_price IS '[U] Unit Sale Price';
COMMENT ON COLUMN cdk_counter_parts_sale.sale_date IS '[U] Sale Date';
COMMENT ON COLUMN cdk_counter_parts_sale.transaction_code IS '[D] CDK Parts Transaction Code (values: (blank)/N=Normal sale/return; W=Warranty sale; H=Wholesale sale; M=Minus adjustment; P=Plus adjustment; L=Lost sale)';
COMMENT ON COLUMN cdk_counter_parts_sale.invoice_number IS '[U] Invoice Number';
COMMENT ON COLUMN cdk_counter_parts_sale._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_counter_parts_sale._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_counter_parts_sale._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_counter_parts_sale._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_counter_parts_sale ADD CONSTRAINT fk_cdk_counter_parts_sale_customer_id FOREIGN KEY (customer_id) REFERENCES cdk_customer_master (customer_id);
ALTER TABLE cdk_counter_parts_sale ADD CONSTRAINT fk_cdk_counter_parts_sale_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number);
