-- cdk_customer_master (customer-master) -- Customer Master
-- Customer
-- SAP analogue: KNA1 (General Customer Master) / KNB1 (Company Code Data)
-- grain: one row per customer per rooftop
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_customer_master (
    customer_id varchar(32) NOT NULL,
    host_item_id varchar(32),
    first_name varchar(40),
    middle_name varchar(40),
    last_name varchar(40),
    full_name varchar(120),
    company_name varchar(80),
    name_suffix varchar(10),
    title varchar(10),
    secondary_first_name varchar(40),
    secondary_last_name varchar(40),
    secondary_full_name varchar(120),
    secondary_company_name varchar(80),
    birth_day varchar(2),
    birth_month varchar(2),
    birth_year varchar(4),
    address_line1 varchar(60),
    address_line2 varchar(60),
    city varchar(40),
    county varchar(40),
    state varchar(10),
    postal_code varchar(15),
    country varchar(40),
    primary_phone varchar(20),
    home_phone varchar(20),
    secondary_home_phone varchar(20),
    mobile_phone varchar(20),
    business_phone varchar(20),
    business_phone_ext varchar(10),
    home_fax varchar(20),
    work_fax varchar(20),
    pager_number varchar(20),
    text_message_phone varchar(20),
    text_message_carrier varchar(30),
    email_address varchar(120),
    email_type varchar(32),
    preferred_contact_method varchar(32),
    preferred_contact varchar(32),
    preferred_day varchar(32),
    preferred_time varchar(32),
    block_email_flag boolean,
    block_mail_flag boolean,
    block_phone_flag boolean,
    gender varchar(32),
    employer varchar(80),
    language_preference varchar(10),
    comment varchar(255),
    comment_date date,
    date_added date,
    last_updated date,
    parts_flag boolean,
    parts_type varchar(32),
    parts_counter_code varchar(10),
    service_customer_code varchar(2),
    mailability_index varchar(2),
    name_control_code varchar(4),
    tax_code varchar(10),
    default_sale_type varchar(10),
    is_delete_data_flag boolean,
    delete_data_date date,
    delete_data_time varchar(8),
    opt_out_flag boolean,
    opt_out_date date,
    opt_out_time varchar(8),
    casl_consent_timestamp timestamptz,
    overdue_30_days numeric(13,2),
    overdue_60_days numeric(13,2),
    overdue_90_days numeric(13,2),
    overdue_120_days numeric(13,2),
    current_balance numeric(13,2),
    credit_limit numeric(13,2),
    current_due numeric(13,2),
    insurance_policy_number varchar(40),
    insurance_policy_expiration date,
    insurance_company_name varchar(80),
    insurance_agent_name varchar(80),
    special_instructions_line1 varchar(80),
    special_instructions_line2 varchar(80),
    special_instructions_line3 varchar(80),
    special_instructions_line4 varchar(80),
    special_instructions_line5 varchar(80),
    crm_customer_id varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (customer_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_customer_master.customer_id IS '[D] Customer ID [WIDENED per WIDENING-POLICY.md: SAP KNA1-KUNNR is CHAR(10); DDL emits source-native 32]';
COMMENT ON COLUMN cdk_customer_master.host_item_id IS '[D] Host Item ID [WIDENED per WIDENING-POLICY.md: SAP KNA1-KUNNR is CHAR(10); DDL emits source-native 32]';
COMMENT ON COLUMN cdk_customer_master.first_name IS '[D] First Name [WIDENED per WIDENING-POLICY.md: SAP KNA1-NAME2 is CHAR(35); DDL emits source-native 40]';
COMMENT ON COLUMN cdk_customer_master.middle_name IS '[D] Middle Name';
COMMENT ON COLUMN cdk_customer_master.last_name IS '[D] Last Name [WIDENED per WIDENING-POLICY.md: SAP KNA1-NAME1 is CHAR(35); DDL emits source-native 40]';
COMMENT ON COLUMN cdk_customer_master.full_name IS '[D] Full Name';
COMMENT ON COLUMN cdk_customer_master.company_name IS '[D] Company Name [WIDENED per WIDENING-POLICY.md: SAP KNA1-NAME1 is CHAR(35); DDL emits source-native 80]';
COMMENT ON COLUMN cdk_customer_master.name_suffix IS '[D] Name Suffix';
COMMENT ON COLUMN cdk_customer_master.title IS '[D] Title';
COMMENT ON COLUMN cdk_customer_master.secondary_first_name IS '[D] Secondary First Name';
COMMENT ON COLUMN cdk_customer_master.secondary_last_name IS '[D] Secondary Last Name';
COMMENT ON COLUMN cdk_customer_master.secondary_full_name IS '[D] Secondary Full Name';
COMMENT ON COLUMN cdk_customer_master.secondary_company_name IS '[D] Secondary Company Name';
COMMENT ON COLUMN cdk_customer_master.birth_day IS '[D] Birth Day';
COMMENT ON COLUMN cdk_customer_master.birth_month IS '[D] Birth Month';
COMMENT ON COLUMN cdk_customer_master.birth_year IS '[D] Birth Year';
COMMENT ON COLUMN cdk_customer_master.address_line1 IS '[D] Address Line 1 [WIDENED per WIDENING-POLICY.md: SAP KNA1-STRAS is CHAR(35); DDL emits source-native 60]';
COMMENT ON COLUMN cdk_customer_master.address_line2 IS '[D] Address Line 2';
COMMENT ON COLUMN cdk_customer_master.city IS '[D] City [WIDENED per WIDENING-POLICY.md: SAP KNA1-ORT01 is CHAR(35); DDL emits source-native 40]';
COMMENT ON COLUMN cdk_customer_master.county IS '[D] County';
COMMENT ON COLUMN cdk_customer_master.state IS '[D] State [WIDENED per WIDENING-POLICY.md: SAP KNA1-REGIO is CHAR(3); DDL emits source-native 10]';
COMMENT ON COLUMN cdk_customer_master.postal_code IS '[D] Postal Code [WIDENED per WIDENING-POLICY.md: SAP KNA1-PSTLZ is CHAR(10); DDL emits source-native 15]';
COMMENT ON COLUMN cdk_customer_master.country IS '[D] Country [WIDENED per WIDENING-POLICY.md: SAP KNA1-LAND1 is CHAR(3); DDL emits source-native 40]';
COMMENT ON COLUMN cdk_customer_master.primary_phone IS '[D] Primary Phone [WIDENED per WIDENING-POLICY.md: SAP KNA1-TELF1 is CHAR(16); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_customer_master.home_phone IS '[D] Home Phone';
COMMENT ON COLUMN cdk_customer_master.secondary_home_phone IS '[D] Secondary Home Phone';
COMMENT ON COLUMN cdk_customer_master.mobile_phone IS '[D] Mobile Phone [WIDENED per WIDENING-POLICY.md: SAP KNA1-TELF2 is CHAR(16); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_customer_master.business_phone IS '[D] Business Phone';
COMMENT ON COLUMN cdk_customer_master.business_phone_ext IS '[D] Business Phone Ext';
COMMENT ON COLUMN cdk_customer_master.home_fax IS '[D] Home Fax';
COMMENT ON COLUMN cdk_customer_master.work_fax IS '[D] Work Fax';
COMMENT ON COLUMN cdk_customer_master.pager_number IS '[D] Pager Number';
COMMENT ON COLUMN cdk_customer_master.text_message_phone IS '[D] Text Message Phone';
COMMENT ON COLUMN cdk_customer_master.text_message_carrier IS '[D] Text Message Carrier';
COMMENT ON COLUMN cdk_customer_master.email_address IS '[D] Email Address';
COMMENT ON COLUMN cdk_customer_master.email_type IS '[D] Email Type (values: CELL=Cell; HOME=Home (default); WORK=Work; PDA/LAPTOP=PDA/Laptop; VEHICLE=Vehicle; OTHER=Other; NA=Non-applicable; CD=Customer declined to add)';
COMMENT ON COLUMN cdk_customer_master.preferred_contact_method IS '[D] Preferred Contact Method (values: B=Work FAX; D=Do Not Disturb/Contact; E=Email address; F=Home FAX; M=Postal mail; P=Pager; T=Main Telephone; X=Text message)';
COMMENT ON COLUMN cdk_customer_master.preferred_contact IS '[D] Preferred Contact (record-level) (values: C=Cellular/mobile phone; E=Email; F=Home Fax; H=Home Phone; M=Mail; P=Pager; W=Work phone; null=No preference)';
COMMENT ON COLUMN cdk_customer_master.preferred_day IS '[D] Preferred Day (values: 1=Monday; 2=Tuesday; 3=Wednesday; 4=Thursday; 5=Friday; 6=Saturday; 7=Sunday)';
COMMENT ON COLUMN cdk_customer_master.preferred_time IS '[D] Preferred Time (values: AM=Morning; PM=Afternoon/evening)';
COMMENT ON COLUMN cdk_customer_master.block_email_flag IS '[D] Block Email Flag';
COMMENT ON COLUMN cdk_customer_master.block_mail_flag IS '[D] Block Mail Flag';
COMMENT ON COLUMN cdk_customer_master.block_phone_flag IS '[D] Block Phone Flag';
COMMENT ON COLUMN cdk_customer_master.gender IS '[D] Gender (values: F=Female; M=Male)';
COMMENT ON COLUMN cdk_customer_master.employer IS '[D] Employer';
COMMENT ON COLUMN cdk_customer_master.language_preference IS '[D] Language Preference';
COMMENT ON COLUMN cdk_customer_master.comment IS '[D] Comment';
COMMENT ON COLUMN cdk_customer_master.comment_date IS '[D] Comment Date';
COMMENT ON COLUMN cdk_customer_master.date_added IS '[D] Date Added';
COMMENT ON COLUMN cdk_customer_master.last_updated IS '[D] Last Updated';
COMMENT ON COLUMN cdk_customer_master.parts_flag IS '[D] Parts Customer Flag';
COMMENT ON COLUMN cdk_customer_master.parts_type IS '[D] Parts Type (values: W=Wholesale customer; null=No type)';
COMMENT ON COLUMN cdk_customer_master.parts_counter_code IS '[D] Parts Counter Code';
COMMENT ON COLUMN cdk_customer_master.service_customer_code IS '[D] Service Customer Code (values: S=Service-only (non-AR/Parts) customer)';
COMMENT ON COLUMN cdk_customer_master.mailability_index IS '[D] Mailability Index (values: 1-9=Primary partner mailability index tiers; X=Excluded/undeliverable)';
COMMENT ON COLUMN cdk_customer_master.name_control_code IS '[D] Name Control Code';
COMMENT ON COLUMN cdk_customer_master.tax_code IS '[D] Sold-To Tax Code';
COMMENT ON COLUMN cdk_customer_master.default_sale_type IS '[D] Default Sale Type';
COMMENT ON COLUMN cdk_customer_master.is_delete_data_flag IS '[D] CCPA Delete-Data Flag';
COMMENT ON COLUMN cdk_customer_master.delete_data_date IS '[D] CCPA Delete Data Date';
COMMENT ON COLUMN cdk_customer_master.delete_data_time IS '[D] CCPA Delete Data Time';
COMMENT ON COLUMN cdk_customer_master.opt_out_flag IS '[D] Privacy Opt-Out Flag';
COMMENT ON COLUMN cdk_customer_master.opt_out_date IS '[D] Privacy Opt-Out Date';
COMMENT ON COLUMN cdk_customer_master.opt_out_time IS '[D] Privacy Opt-Out Time';
COMMENT ON COLUMN cdk_customer_master.casl_consent_timestamp IS '[U] CASL Consent Timestamp (gap)';
COMMENT ON COLUMN cdk_customer_master.overdue_30_days IS '[D] Balance Over 30 Days';
COMMENT ON COLUMN cdk_customer_master.overdue_60_days IS '[D] Balance Over 60 Days';
COMMENT ON COLUMN cdk_customer_master.overdue_90_days IS '[D] Balance Over 90 Days';
COMMENT ON COLUMN cdk_customer_master.overdue_120_days IS '[D] Balance Over 120 Days';
COMMENT ON COLUMN cdk_customer_master.current_balance IS '[D] Current Balance';
COMMENT ON COLUMN cdk_customer_master.credit_limit IS '[D] Credit Limit';
COMMENT ON COLUMN cdk_customer_master.current_due IS '[D] Current Amount Due';
COMMENT ON COLUMN cdk_customer_master.insurance_policy_number IS '[D] Insurance Policy Number';
COMMENT ON COLUMN cdk_customer_master.insurance_policy_expiration IS '[D] Insurance Policy Expiration';
COMMENT ON COLUMN cdk_customer_master.insurance_company_name IS '[D] Insurance Company Name';
COMMENT ON COLUMN cdk_customer_master.insurance_agent_name IS '[D] Insurance Agent Name';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line1 IS '[D] Special Instructions Line 1';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line2 IS '[D] Special Instructions Line 2';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line3 IS '[D] Special Instructions Line 3';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line4 IS '[D] Special Instructions Line 4';
COMMENT ON COLUMN cdk_customer_master.special_instructions_line5 IS '[D] Special Instructions Line 5';
COMMENT ON COLUMN cdk_customer_master.crm_customer_id IS '[D] CRM Customer ID (Customers API v1)';
COMMENT ON COLUMN cdk_customer_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_customer_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_customer_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_customer_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_customer_master ADD CONSTRAINT fk_cdk_customer_master_crm_customer_id FOREIGN KEY (crm_customer_id) REFERENCES cdk_customer_master (customer_id);
