-- cdk_deal_jacket_vehicle_sale (deal-jacket-vehicle-sale) -- Deal Jacket / Vehicle Sale
-- Deal Jacket
-- SAP analogue: VBAK/VBAP (Sales Order) + posted Billing Document — closest SAP analogue for a vehicle sale + F&I bundle
-- grain: one row per deal per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_deal_jacket_vehicle_sale (
    deal_id varchar(20),
    deal_status varchar(32),
    deal_lifecycle_stage varchar(32),
    customer_id varchar(32),
    vehicle_id varchar(32),
    sale_price numeric(13,2),
    trade_in_vehicle_id varchar(32),
    finance_source_lender_id varchar(20),
    we_owe_description varchar(120),
    deal_type varchar(32),
    fi_products_sold varchar(255),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (deal_id)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on deal_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on deal_status: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)
    -- NOT NULL withheld on deal_lifecycle_stage: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.deal_id IS '[I] Deal ID';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.deal_status IS '[U] Deal / FI Sales Status (values: C=Likely: Cancelled (unconfirmed); B=Likely: Booked (unconfirmed); P=Likely: Pending (unconfirmed); F=Likely: Finalized (unconfirmed); I=Likely: Incomplete (unconfirmed); U=Likely: Unknown/Unposted (unconfirmed))';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.deal_lifecycle_stage IS '[I] Deal Lifecycle Stage (documented chain) (values: PROSPECT=Prospect; QUOTE_DESK=Quote / Desk deal; PENDING_DEAL=Pending Deal; WE_OWE=We-Owe(s); FINALIZED_BOOKED=Finalized (Booked) Deal; POSTED=Posted Vehicle Sale + F&I schedule entries)';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.customer_id IS '[U] Customer ID';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.vehicle_id IS '[U] Vehicle ID (VIN)';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.sale_price IS '[U] Vehicle Sale Price';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.trade_in_vehicle_id IS '[U] Trade-In Vehicle ID';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.finance_source_lender_id IS '[U] Finance Source / Lender ID';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.we_owe_description IS '[I] We-Owe Item Description';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.deal_type IS '[I] Deal Type (values: CASH=Cash deal; FINANCE=Finance deal; LEASE=Lease deal)';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale.fi_products_sold IS '[U] F&I Products Sold';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_deal_jacket_vehicle_sale._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_deal_jacket_vehicle_sale ADD CONSTRAINT fk_cdk_deal_jacket_vehicle_sale_customer_id FOREIGN KEY (customer_id) REFERENCES cdk_customer_master (customer_id);
ALTER TABLE cdk_deal_jacket_vehicle_sale ADD CONSTRAINT fk_cdk_deal_jacket_vehicle_sale_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES cdk_vehicle_master (vehicle_id);
ALTER TABLE cdk_deal_jacket_vehicle_sale ADD CONSTRAINT fk_cdk_deal_jacket_vehicle_sale_trade_in_vehicle_id FOREIGN KEY (trade_in_vehicle_id) REFERENCES cdk_vehicle_master (vehicle_id);
ALTER TABLE cdk_deal_jacket_vehicle_sale ADD CONSTRAINT fk_cdk_deal_jacket_vehicle_sale_finance_source_lender_id FOREIGN KEY (finance_source_lender_id) REFERENCES cdk_vendor_master (vendor_id);
