-- cdk_dealer_rooftop_partition (dealer-rooftop-partition) -- Dealer Rooftop Partition
-- Rooftop / Store / Company
-- SAP analogue: Company Code (Buchungskreis) / Client (Mandant)
-- grain: one row per rooftop-department binding (Subscription-Id x Department-Id)
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_dealer_rooftop_partition (
    subscription_id varchar(64) NOT NULL,
    department_id varchar(32) NOT NULL,
    request_id varchar(64) NOT NULL,
    company_number varchar(10),
    cmf_client_number varchar(10),
    dms_type varchar(20) NOT NULL,
    rooftop_name varchar(120),
    rooftop_address varchar(255),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (subscription_id, department_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_dealer_rooftop_partition.subscription_id IS '[D] Subscription-Id';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.department_id IS '[D] Department-Id';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.request_id IS '[D] Request-Id';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.company_number IS '[U] Co #';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.cmf_client_number IS '[U] Client #';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.dms_type IS '[D] DMS Type (values: Accounting=Accounting DMS module; Finance=Finance/F&I DMS module; Inventory=Vehicle inventory DMS module; Parts=Parts DMS module; Service=Service DMS module)';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.rooftop_name IS '[I] Dealer Name';
COMMENT ON COLUMN cdk_dealer_rooftop_partition.rooftop_address IS '[I] Dealer Address';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_dealer_rooftop_partition._batch_id IS '[D] the extract run/batch identifier this row landed with';
