-- cdk_employee_master (employee-master) -- Employee Master
-- Employee
-- SAP analogue: PA0001 / PA0002 (HR master infotypes) — closest SAP analogue
-- grain: one row per employee per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_employee_master (
    employee_key varchar(24),
    service_advisor_number bigint,
    cashier_id varchar(10),
    booker_number bigint,
    story_employee_number varchar(10),
    technician_ids varchar(40),
    comeback_service_advisor varchar(10),
    comeback_technician varchar(10),
    hours_technician_id bigint,
    parts_counter_employee_id bigint,
    outside_salesman_id bigint,
    punch_technician_id bigint,
    discount_user_id varchar(20),
    discount_applied_by varchar(20),
    manager_override_id varchar(20),
    lookup_technician_id varchar(10),
    lookup_service_advisor_id varchar(10),
    employee_name varchar(80),
    employee_department varchar(10),
    employee_status varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (employee_key)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on employee_key: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_employee_master.employee_key IS '[U] the one person behind all these different ID columns';
COMMENT ON COLUMN cdk_employee_master.service_advisor_number IS '[D] Service Advisor Number';
COMMENT ON COLUMN cdk_employee_master.cashier_id IS '[D] Cashier ID';
COMMENT ON COLUMN cdk_employee_master.booker_number IS '[D] Booker Number';
COMMENT ON COLUMN cdk_employee_master.story_employee_number IS '[D] Story Employee Number';
COMMENT ON COLUMN cdk_employee_master.technician_ids IS '[D] Technician ID(s)';
COMMENT ON COLUMN cdk_employee_master.comeback_service_advisor IS '[D] Comeback Service Advisor';
COMMENT ON COLUMN cdk_employee_master.comeback_technician IS '[D] Comeback Technician';
COMMENT ON COLUMN cdk_employee_master.hours_technician_id IS '[D] Hours-Detail Technician ID';
COMMENT ON COLUMN cdk_employee_master.parts_counter_employee_id IS '[D] Parts Counter Employee ID';
COMMENT ON COLUMN cdk_employee_master.outside_salesman_id IS '[D] Outside Salesman ID';
COMMENT ON COLUMN cdk_employee_master.punch_technician_id IS '[D] Punch Clock Technician ID';
COMMENT ON COLUMN cdk_employee_master.discount_user_id IS '[D] Discount User ID';
COMMENT ON COLUMN cdk_employee_master.discount_applied_by IS '[D] Discount Applied By';
COMMENT ON COLUMN cdk_employee_master.manager_override_id IS '[D] Manager Override ID';
COMMENT ON COLUMN cdk_employee_master.lookup_technician_id IS '[I] Technician Lookup ID';
COMMENT ON COLUMN cdk_employee_master.lookup_service_advisor_id IS '[I] Service Advisor Lookup ID';
COMMENT ON COLUMN cdk_employee_master.employee_name IS '[U] Employee Name';
COMMENT ON COLUMN cdk_employee_master.employee_department IS '[U] Employee Department';
COMMENT ON COLUMN cdk_employee_master.employee_status IS '[U] Employee Active/Terminated Status (values: ACTIVE=Active employee; TERMINATED=Terminated employee)';
COMMENT ON COLUMN cdk_employee_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_employee_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_employee_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_employee_master._batch_id IS '[D] the extract run/batch identifier this row landed with';
