-- cdk_gl_journal_posting (gl-journal-posting) -- GL Journal Posting
-- Journal Entry
-- SAP analogue: BKPF (Accounting Document Header) / BSEG (Accounting Document Segment)
-- grain: one row per journal line per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_gl_journal_posting (
    document_number varchar(20),
    journal_number varchar(20),
    journal_type varchar(32) NOT NULL,
    gl_account_number varchar(10),
    schedule_field varchar(32),
    adjust_to_gl_account varchar(10),
    posting_date date,
    debit_amount numeric(13,2),
    credit_amount numeric(13,2),
    wip_endpoint_used varchar(32),
    source_module varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (document_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on document_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on gl_account_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on posting_date: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_gl_journal_posting.document_number IS '[I] Document Number';
COMMENT ON COLUMN cdk_gl_journal_posting.journal_number IS '[I] Journal Number';
COMMENT ON COLUMN cdk_gl_journal_posting.journal_type IS '[D] Journal Type (values: STANDARD_ENTRIES=Standard Entries Journal; CASH_RECEIPTS=Cash Receipts Journal; CASH_DISBURSEMENTS=Cash Disbursements Journal; PURCHASE=Purchase Journal; PAYROLL=Payroll Journal; NEW_VEHICLE_SALES_PURCHASE=New Vehicle Sales/Purchase Journal; USED_CAR_SALES=Used Car Sales Journal; INTERNAL_SALES=Internal Sales Journal; SERVICE_SALES_CASH=Service Sales (Cash) Journal; SERVICE_SALES_CHARGE=Service Sales (Charge) Journal; WARRANTY_SALES=Warranty Sales Journal; PARTS_SALES_CASH=Parts Sales (Cash) Journal; PARTS_SALES_CHARGE=Parts Sales (Charge) Journal; DEALER_EXCHANGE=Dealer Exchange Journal; STATISTICAL_DATA=Statistical Data Journal; GENERAL_JOURNAL_ENTRY=General Journal Entry)';
COMMENT ON COLUMN cdk_gl_journal_posting.gl_account_number IS '[I] GL Account Number';
COMMENT ON COLUMN cdk_gl_journal_posting.schedule_field IS '[I] Schedule Field / Control Reference';
COMMENT ON COLUMN cdk_gl_journal_posting.adjust_to_gl_account IS '[I] Adjust-To GL Account';
COMMENT ON COLUMN cdk_gl_journal_posting.posting_date IS '[I] Posting Date';
COMMENT ON COLUMN cdk_gl_journal_posting.debit_amount IS '[I] Debit Amount';
COMMENT ON COLUMN cdk_gl_journal_posting.credit_amount IS '[I] Credit Amount';
COMMENT ON COLUMN cdk_gl_journal_posting.wip_endpoint_used IS '[D] WIP Posting Endpoint (values: GL_WIP_POST=cdk/drive/glwippost/startWIP — CDK Drive Post Accounts GL WIP; GL_POST=cdk/drive/glpost/startWIP — CDK Drive Post Accounting GL)';
COMMENT ON COLUMN cdk_gl_journal_posting.source_module IS '[I] Source Module (values: SERVICE=Service (RO close); PARTS=Parts; FI=F&I / Vehicle Sale; AP=Accounts Payable; AR=Accounts Receivable; PAYROLL=Payroll)';
COMMENT ON COLUMN cdk_gl_journal_posting._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_gl_journal_posting._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_gl_journal_posting._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_gl_journal_posting._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_gl_journal_posting ADD CONSTRAINT fk_cdk_gl_journal_posting_gl_account_number FOREIGN KEY (gl_account_number) REFERENCES cdk_gl_account_master (gl_account_number);
ALTER TABLE cdk_gl_journal_posting ADD CONSTRAINT fk_cdk_gl_journal_posting_schedule_field FOREIGN KEY (schedule_field) REFERENCES cdk_accounting_schedule (control_key_value);
ALTER TABLE cdk_gl_journal_posting ADD CONSTRAINT fk_cdk_gl_journal_posting_adjust_to_gl_account FOREIGN KEY (adjust_to_gl_account) REFERENCES cdk_gl_account_master (gl_account_number);
