-- cdk_parts_order_supersession (parts-order-supersession) -- Parts Order / Supersession
-- Parts Order & Supersession
-- SAP analogue: MMPUR (Purchase Order) / MARA-supersession chain (custom Z-table analogue)
-- grain: one row per parts order line, or one row per supersession chain hop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_parts_order_supersession (
    order_type varchar(32) NOT NULL,
    ordering_platform varchar(40),
    cdk_function_code varchar(32),
    order_number varchar(20),
    part_number varchar(20),
    superseded_by_part_number varchar(20),
    quantity_ordered numeric(13,3),
    order_date date,
    confirmation_status varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (order_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on order_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on part_number: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_parts_order_supersession.order_type IS '[D] PACCAR MDI Order Type (values: STOCK=Stock order; EMERGENCY=Emergency order; MKT=Marketing Suggestion order; COF=Auto Confirmed order)';
COMMENT ON COLUMN cdk_parts_order_supersession.ordering_platform IS '[D] Ordering Platform';
COMMENT ON COLUMN cdk_parts_order_supersession.cdk_function_code IS '[I] CDK Ordering Function Code (values: IRO=Stocking parameters; IRE=Generate suggested stock order; PO=Manual order; RMR=Report MO (Manufacturer Order) Review)';
COMMENT ON COLUMN cdk_parts_order_supersession.order_number IS '[I] Order Number';
COMMENT ON COLUMN cdk_parts_order_supersession.part_number IS '[I] Part Number';
COMMENT ON COLUMN cdk_parts_order_supersession.superseded_by_part_number IS '[I] Superseded-By Part Number';
COMMENT ON COLUMN cdk_parts_order_supersession.quantity_ordered IS '[I] Quantity Ordered';
COMMENT ON COLUMN cdk_parts_order_supersession.order_date IS '[I] Order Date';
COMMENT ON COLUMN cdk_parts_order_supersession.confirmation_status IS '[I] Confirmation Status (values: PENDING=Pending confirmation; CONFIRMED=Confirmed; REJECTED=Rejected)';
COMMENT ON COLUMN cdk_parts_order_supersession._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_parts_order_supersession._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_parts_order_supersession._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_parts_order_supersession._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_parts_order_supersession ADD CONSTRAINT fk_cdk_parts_order_supersession_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number);
ALTER TABLE cdk_parts_order_supersession ADD CONSTRAINT fk_cdk_parts_order_supersession_superseded_by_part_number FOREIGN KEY (superseded_by_part_number) REFERENCES cdk_parts_master_inventory (part_number);
