-- cdk_parts_master_inventory (parts-master-inventory) -- Parts Master / Inventory
-- Parts Inventory
-- SAP analogue: MARA (Material Master) / MARD (Storage Location Data) / MBEW (Material Valuation)
-- grain: one row per part number per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_parts_master_inventory (
    part_number varchar(20) NOT NULL,
    description varchar(60),
    manufacturer varchar(40),
    quantity_on_hand numeric(13,3),
    bin_location varchar(10),
    bin2_location varchar(10),
    unit_cost numeric(13,2),
    list_price numeric(13,2),
    last_sale_date date,
    date_received date,
    delete_part_flag boolean,
    group_code varchar(10),
    minimum_stock_level numeric(13,3),
    maximum_stock_level numeric(13,3),
    safety_stock_level numeric(13,3),
    supersession_successor_part_number varchar(20),
    part_condition_code varchar(32),
    vmrs_code varchar(10),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (part_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_parts_master_inventory.part_number IS '[D] Part Number [WIDENED per WIDENING-POLICY.md: SAP MARA-MATNR is CHAR(18); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_parts_master_inventory.description IS '[D] Description';
COMMENT ON COLUMN cdk_parts_master_inventory.manufacturer IS '[D] Manufacturer';
COMMENT ON COLUMN cdk_parts_master_inventory.quantity_on_hand IS '[D] Quantity On Hand';
COMMENT ON COLUMN cdk_parts_master_inventory.bin_location IS '[D] Bin Location';
COMMENT ON COLUMN cdk_parts_master_inventory.bin2_location IS '[I] Alternate Bin Location';
COMMENT ON COLUMN cdk_parts_master_inventory.unit_cost IS '[D] Unit Cost';
COMMENT ON COLUMN cdk_parts_master_inventory.list_price IS '[D] List Price';
COMMENT ON COLUMN cdk_parts_master_inventory.last_sale_date IS '[D] Last Sale Date';
COMMENT ON COLUMN cdk_parts_master_inventory.date_received IS '[D] Date Received';
COMMENT ON COLUMN cdk_parts_master_inventory.delete_part_flag IS '[D] Delete Part Flag';
COMMENT ON COLUMN cdk_parts_master_inventory.group_code IS '[D] Group Code';
COMMENT ON COLUMN cdk_parts_master_inventory.minimum_stock_level IS '[D] Minimum Stock Level';
COMMENT ON COLUMN cdk_parts_master_inventory.maximum_stock_level IS '[D] Maximum Stock Level';
COMMENT ON COLUMN cdk_parts_master_inventory.safety_stock_level IS '[D] Safety Stock Level';
COMMENT ON COLUMN cdk_parts_master_inventory.supersession_successor_part_number IS '[I] Supersession Chain — Successor Part Number';
COMMENT ON COLUMN cdk_parts_master_inventory.part_condition_code IS '[I] Part Condition Code (STAR analogue) (values: NEW=New part; CORE=Core/remanufactured-eligible; REMAN=Remanufactured part)';
COMMENT ON COLUMN cdk_parts_master_inventory.vmrs_code IS '[I] VMRS Code';
COMMENT ON COLUMN cdk_parts_master_inventory._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_parts_master_inventory._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_parts_master_inventory._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_parts_master_inventory._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_parts_master_inventory ADD CONSTRAINT fk_cdk_parts_master_inventory_supersession_successor_part_number FOREIGN KEY (supersession_successor_part_number) REFERENCES cdk_parts_master_inventory (part_number);
