-- cdk_purchase_receipt_document (purchase-receipt-document) -- Purchase / Receipt Document
-- Purchase Order & Receipt
-- SAP analogue: EKKO/EKPO (Purchase Order Header/Item) + MSEG (Material Document, Movement Type 101 Goods Receipt)
-- grain: one row per PO line receipt
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_purchase_receipt_document (
    purchase_order_number varchar(20),
    vendor_id varchar(20),
    po_date date,
    po_line_number bigint,
    part_number varchar(20),
    quantity_ordered numeric(13,3),
    quantity_received numeric(13,3),
    receipt_document_number varchar(20),
    receipt_date date,
    asn_number varchar(30),
    invoice_number varchar(20),
    unit_cost numeric(13,2),
    three_way_match_status varchar(32),
    ap_posting_gl_account varchar(10),
    movement_type_sap_analogue varchar(4),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (purchase_order_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on purchase_order_number: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)
    -- NOT NULL withheld on vendor_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)
    -- NOT NULL withheld on po_line_number: nullable=false per source but confidence=UNVERIFIED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_purchase_receipt_document.purchase_order_number IS '[U] Purchase Order Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.vendor_id IS '[I] Vendor ID';
COMMENT ON COLUMN cdk_purchase_receipt_document.po_date IS '[U] PO Date';
COMMENT ON COLUMN cdk_purchase_receipt_document.po_line_number IS '[U] PO Line Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.part_number IS '[I] Part Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.quantity_ordered IS '[U] Quantity Ordered';
COMMENT ON COLUMN cdk_purchase_receipt_document.quantity_received IS '[I] Quantity Received';
COMMENT ON COLUMN cdk_purchase_receipt_document.receipt_document_number IS '[U] Receipt (GR) Document Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.receipt_date IS '[I] Receipt Date';
COMMENT ON COLUMN cdk_purchase_receipt_document.asn_number IS '[I] Advance Ship Notice (ASN) Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.invoice_number IS '[I] Vendor Invoice Number';
COMMENT ON COLUMN cdk_purchase_receipt_document.unit_cost IS '[U] Unit Cost (Invoiced)';
COMMENT ON COLUMN cdk_purchase_receipt_document.three_way_match_status IS '[I] Three-Way Match Status (values: MATCHED=PO, receipt, and invoice all agree; QTY_VARIANCE=Quantity variance between receipt and invoice; PRICE_VARIANCE=Price variance between PO and invoice; UNMATCHED=Not yet matched)';
COMMENT ON COLUMN cdk_purchase_receipt_document.ap_posting_gl_account IS '[I] AP Posting GL Account';
COMMENT ON COLUMN cdk_purchase_receipt_document.movement_type_sap_analogue IS '[I] Movement Type (SAP Analogue)';
COMMENT ON COLUMN cdk_purchase_receipt_document._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_purchase_receipt_document._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_purchase_receipt_document._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_purchase_receipt_document._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_vendor_id FOREIGN KEY (vendor_id) REFERENCES cdk_vendor_master (vendor_id);
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number);
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_invoice_number FOREIGN KEY (invoice_number) REFERENCES cdk_vendor_master (vendor_id);
ALTER TABLE cdk_purchase_receipt_document ADD CONSTRAINT fk_cdk_purchase_receipt_document_ap_posting_gl_account FOREIGN KEY (ap_posting_gl_account) REFERENCES cdk_gl_account_master (gl_account_number);
