-- cdk_ro_labour_line (ro-labour-line) -- Repair Order Labour Line
-- RO Labor Line
-- SAP analogue: AFVC (Operation within an Order) / CATSDB (time confirmation)
-- grain: one row per labor operation per repair order
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_ro_labour_line (
    ro_number varchar(12) NOT NULL,
    line_code varchar(6) NOT NULL,
    line_status_code varchar(10),
    line_status_desc varchar(40),
    complaint_code varchar(10),
    cause varchar(255),
    service_request_text varchar(255),
    dispatch_code varchar(10),
    campaign_code varchar(10),
    line_comeback_flag boolean,
    line_add_on_flag boolean,
    actual_work_hours numeric(9,3),
    estimated_duration_hours numeric(9,3),
    story_text varchar(1000),
    story_sequence_number bigint,
    labor_op_sequence_number bigint NOT NULL,
    labor_op_code varchar(10) NOT NULL,
    labor_op_desc varchar(80),
    labor_type_code varchar(6),
    technician_ids varchar(40),
    sold_hours numeric(9,3),
    actual_hours numeric(9,3),
    flag_hours numeric(9,3),
    time_card_hours numeric(9,3),
    other_hours numeric(9,3),
    labor_sale_amount numeric(13,2),
    labor_cost_amount numeric(13,2),
    forced_shop_charge numeric(13,2),
    mcd_percentage numeric(7,4),
    labor_op_comeback_flag boolean,
    comeback_original_ro_number varchar(20),
    labor_op_booked_date date,
    hour_type_code varchar(6),
    hours_labor_type varchar(6),
    hours_percentage numeric(7,4),
    fee_type_code varchar(32),
    fee_sale_amount numeric(13,2),
    line_warranty_claim_type varchar(10),
    line_warranty_auth_code varchar(20),
    line_warranty_failed_part_no varchar(20),
    effective_labor_rate_kpi numeric(13,2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (ro_number, line_code, labor_op_sequence_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_ro_labour_line.ro_number IS '[D] the RO number this job belongs to';
COMMENT ON COLUMN cdk_ro_labour_line.line_code IS '[D] Repair Line Code';
COMMENT ON COLUMN cdk_ro_labour_line.line_status_code IS '[D] Line Status Code';
COMMENT ON COLUMN cdk_ro_labour_line.line_status_desc IS '[D] Line Status Description';
COMMENT ON COLUMN cdk_ro_labour_line.complaint_code IS '[D] Complaint Code';
COMMENT ON COLUMN cdk_ro_labour_line.cause IS '[D] Cause';
COMMENT ON COLUMN cdk_ro_labour_line.service_request_text IS '[D] Service Request Text';
COMMENT ON COLUMN cdk_ro_labour_line.dispatch_code IS '[D] Dispatch Code';
COMMENT ON COLUMN cdk_ro_labour_line.campaign_code IS '[D] Campaign Code';
COMMENT ON COLUMN cdk_ro_labour_line.line_comeback_flag IS '[D] Line Comeback Flag';
COMMENT ON COLUMN cdk_ro_labour_line.line_add_on_flag IS '[D] Line Add-On Flag';
COMMENT ON COLUMN cdk_ro_labour_line.actual_work_hours IS '[D] Actual Work Hours';
COMMENT ON COLUMN cdk_ro_labour_line.estimated_duration_hours IS '[D] Estimated Duration';
COMMENT ON COLUMN cdk_ro_labour_line.story_text IS '[D] Technician Story Text';
COMMENT ON COLUMN cdk_ro_labour_line.story_sequence_number IS '[D] Story Sequence Number';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_sequence_number IS '[D] Labor Operation Sequence Number';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_code IS '[D] Labor Operation Code [WIDENED per WIDENING-POLICY.md: SAP AFVC-STEUS is CHAR(4); DDL emits source-native 10]';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_desc IS '[D] Labor Operation Description';
COMMENT ON COLUMN cdk_ro_labour_line.labor_type_code IS '[D] Labor Type Code';
COMMENT ON COLUMN cdk_ro_labour_line.technician_ids IS '[D] Technician ID(s)';
COMMENT ON COLUMN cdk_ro_labour_line.sold_hours IS '[D] Sold Hours';
COMMENT ON COLUMN cdk_ro_labour_line.actual_hours IS '[D] Actual Hours';
COMMENT ON COLUMN cdk_ro_labour_line.flag_hours IS '[D] Flagged Hours';
COMMENT ON COLUMN cdk_ro_labour_line.time_card_hours IS '[D] Time Card Hours';
COMMENT ON COLUMN cdk_ro_labour_line.other_hours IS '[D] Other Hours';
COMMENT ON COLUMN cdk_ro_labour_line.labor_sale_amount IS '[D] Labor Sale Amount';
COMMENT ON COLUMN cdk_ro_labour_line.labor_cost_amount IS '[D] Labor Cost Amount';
COMMENT ON COLUMN cdk_ro_labour_line.forced_shop_charge IS '[D] Forced Shop Charge';
COMMENT ON COLUMN cdk_ro_labour_line.mcd_percentage IS '[D] Split-Op MCD Percentage';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_comeback_flag IS '[D] Labor Op Comeback Flag';
COMMENT ON COLUMN cdk_ro_labour_line.comeback_original_ro_number IS '[D] Comeback Original RO Number';
COMMENT ON COLUMN cdk_ro_labour_line.labor_op_booked_date IS '[D] Labor Op Booked Date';
COMMENT ON COLUMN cdk_ro_labour_line.hour_type_code IS '[D] Hour Type Code';
COMMENT ON COLUMN cdk_ro_labour_line.hours_labor_type IS '[D] Hours-Detail Labor Type';
COMMENT ON COLUMN cdk_ro_labour_line.hours_percentage IS '[D] Technician Actual-Hours Percentage';
COMMENT ON COLUMN cdk_ro_labour_line.fee_type_code IS '[D] Fee Type Code (values: L=Lube; M=Miscellaneous; S=Sublet)';
COMMENT ON COLUMN cdk_ro_labour_line.fee_sale_amount IS '[D] Fee Sale Amount';
COMMENT ON COLUMN cdk_ro_labour_line.line_warranty_claim_type IS '[D] Warranty Claim Type (line-level)';
COMMENT ON COLUMN cdk_ro_labour_line.line_warranty_auth_code IS '[D] Warranty Authorization Code (line-level)';
COMMENT ON COLUMN cdk_ro_labour_line.line_warranty_failed_part_no IS '[D] Failed Part Number (line-level)';
COMMENT ON COLUMN cdk_ro_labour_line.effective_labor_rate_kpi IS '[I] Effective Labor Rate (derived KPI)';
COMMENT ON COLUMN cdk_ro_labour_line._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_ro_labour_line._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_ro_labour_line._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_ro_labour_line._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_technician_ids FOREIGN KEY (technician_ids) REFERENCES cdk_employee_master (technician_ids);
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_comeback_original_ro_number FOREIGN KEY (comeback_original_ro_number) REFERENCES cdk_repair_order (ro_number);
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_line_warranty_claim_type FOREIGN KEY (line_warranty_claim_type) REFERENCES cdk_warranty_claim (claim_type);
ALTER TABLE cdk_ro_labour_line ADD CONSTRAINT fk_cdk_ro_labour_line_line_warranty_failed_part_no FOREIGN KEY (line_warranty_failed_part_no) REFERENCES cdk_parts_master_inventory (part_number);
