-- cdk_ro_part_line (ro-part-line) -- Repair Order Part Line
-- RO Parts Line
-- SAP analogue: MSEG (Material Document Segment) / RESB (Reservation)
-- grain: one row per part line per labor operation per repair order
-- api reach: full
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_ro_part_line (
    ro_number varchar(12) NOT NULL,
    part_sequence_number bigint NOT NULL,
    part_number varchar(20) NOT NULL,
    part_description varchar(60),
    bin1_location varchar(10),
    part_source_number varchar(10),
    parts_class_code varchar(10),
    associated_labor_sequence_number bigint,
    part_labor_type varchar(6),
    part_line_code varchar(6) NOT NULL,
    escalated_unit_cost numeric(13,2),
    escalated_unit_list_price numeric(13,2),
    escalated_unit_sale_price numeric(13,2),
    extended_cost numeric(13,2),
    extended_sale numeric(13,2),
    core_cost numeric(13,2),
    core_sale numeric(13,2),
    unit_service_charge numeric(13,2),
    part_mcd_percentage numeric(7,4),
    unit_comp_price numeric(13,2),
    comp_line_code varchar(6),
    quantity_sold numeric(13,3),
    quantity_ordered numeric(13,3),
    quantity_filled numeric(13,3),
    quantity_backordered numeric(13,3),
    quantity_on_hand_at_sale numeric(13,3),
    part_special_status varchar(10),
    counter_person_employee_id bigint,
    outside_salesman_id bigint,
    part_fee_type_code varchar(32),
    fee_lop_or_part_flag varchar(32),
    transaction_code varchar(32),
    star_part_type_code varchar(32),
    hazmat_indicator boolean,
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (ro_number, part_sequence_number, part_line_code)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_ro_part_line.ro_number IS '[D] the RO number this part was sold on';
COMMENT ON COLUMN cdk_ro_part_line.part_sequence_number IS '[D] Part Sequence Number';
COMMENT ON COLUMN cdk_ro_part_line.part_number IS '[D] Part Number';
COMMENT ON COLUMN cdk_ro_part_line.part_description IS '[D] Part Description';
COMMENT ON COLUMN cdk_ro_part_line.bin1_location IS '[D] Main Bin Location';
COMMENT ON COLUMN cdk_ro_part_line.part_source_number IS '[D] Part Source Number';
COMMENT ON COLUMN cdk_ro_part_line.parts_class_code IS '[D] Parts Class Code';
COMMENT ON COLUMN cdk_ro_part_line.associated_labor_sequence_number IS '[D] Associated Labor Sequence Number';
COMMENT ON COLUMN cdk_ro_part_line.part_labor_type IS '[D] Part Labor Type';
COMMENT ON COLUMN cdk_ro_part_line.part_line_code IS '[D] Part Repair Line Code';
COMMENT ON COLUMN cdk_ro_part_line.escalated_unit_cost IS '[D] Escalated Unit Cost';
COMMENT ON COLUMN cdk_ro_part_line.escalated_unit_list_price IS '[D] Escalated Unit List Price';
COMMENT ON COLUMN cdk_ro_part_line.escalated_unit_sale_price IS '[D] Escalated Unit Sale Price';
COMMENT ON COLUMN cdk_ro_part_line.extended_cost IS '[D] Extended Cost';
COMMENT ON COLUMN cdk_ro_part_line.extended_sale IS '[D] Extended Sale';
COMMENT ON COLUMN cdk_ro_part_line.core_cost IS '[D] Core Cost';
COMMENT ON COLUMN cdk_ro_part_line.core_sale IS '[D] Core Sale (Core Charge)';
COMMENT ON COLUMN cdk_ro_part_line.unit_service_charge IS '[D] Unit Service Charge (returns)';
COMMENT ON COLUMN cdk_ro_part_line.part_mcd_percentage IS '[D] Split-Part MCD Percentage';
COMMENT ON COLUMN cdk_ro_part_line.unit_comp_price IS '[D] Unit Comp Price';
COMMENT ON COLUMN cdk_ro_part_line.comp_line_code IS '[D] Comp Repair Line Code';
COMMENT ON COLUMN cdk_ro_part_line.quantity_sold IS '[D] Quantity Sold';
COMMENT ON COLUMN cdk_ro_part_line.quantity_ordered IS '[D] Quantity Ordered';
COMMENT ON COLUMN cdk_ro_part_line.quantity_filled IS '[D] Quantity Filled';
COMMENT ON COLUMN cdk_ro_part_line.quantity_backordered IS '[D] Quantity Backordered';
COMMENT ON COLUMN cdk_ro_part_line.quantity_on_hand_at_sale IS '[D] Quantity On Hand (at time of sale)';
COMMENT ON COLUMN cdk_ro_part_line.part_special_status IS '[D] Part Special Status';
COMMENT ON COLUMN cdk_ro_part_line.counter_person_employee_id IS '[D] Counter Person Employee ID';
COMMENT ON COLUMN cdk_ro_part_line.outside_salesman_id IS '[D] Outside Salesman ID';
COMMENT ON COLUMN cdk_ro_part_line.part_fee_type_code IS '[D] Part Fee Type Code (values: L=Lube; M=Miscellaneous; S=Sublet)';
COMMENT ON COLUMN cdk_ro_part_line.fee_lop_or_part_flag IS '[D] Fee Applies To Labor Or Part Flag (values: L=Labor; P=Part)';
COMMENT ON COLUMN cdk_ro_part_line.transaction_code IS '[D] CDK Parts Transaction Code (values: (blank)/N=Normal sale/return; W=Warranty sale; NW=Warranty return; DS=Warranty drop-ship sale; DW=Warranty drop-ship return; H=Wholesale sale; NH=Wholesale return; M=Minus adjustment; P=Plus adjustment; L=Lost sale (true lost sale))';
COMMENT ON COLUMN cdk_ro_part_line.star_part_type_code IS '[I] STAR PartTypeCode (cross-vendor) (values: H=Manufacturer Part Code; P=Part Number)';
COMMENT ON COLUMN cdk_ro_part_line.hazmat_indicator IS '[I] Hazmat Indicator (STAR analogue)';
COMMENT ON COLUMN cdk_ro_part_line._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_ro_part_line._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_ro_part_line._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_ro_part_line._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_ro_part_line ADD CONSTRAINT fk_cdk_ro_part_line_part_number FOREIGN KEY (part_number) REFERENCES cdk_parts_master_inventory (part_number);
ALTER TABLE cdk_ro_part_line ADD CONSTRAINT fk_cdk_ro_part_line_associated_labor_sequence_number FOREIGN KEY (associated_labor_sequence_number) REFERENCES cdk_ro_labour_line (labor_op_sequence_number);
ALTER TABLE cdk_ro_part_line ADD CONSTRAINT fk_cdk_ro_part_line_counter_person_employee_id FOREIGN KEY (counter_person_employee_id) REFERENCES cdk_employee_master (parts_counter_employee_id);
ALTER TABLE cdk_ro_part_line ADD CONSTRAINT fk_cdk_ro_part_line_outside_salesman_id FOREIGN KEY (outside_salesman_id) REFERENCES cdk_employee_master (outside_salesman_id);
