-- cdk_technician_time_punch (technician-time-punch) -- Technician Time Punch
-- Technician Clock Punch
-- SAP analogue: CATSDB (Time Sheet / Cross-Application Time Sheet)
-- grain: one row per technician clock punch per repair-order line per work date
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_technician_time_punch (
    technician_id bigint NOT NULL,
    line_code varchar(6) NOT NULL,
    work_date date NOT NULL,
    time_on text NOT NULL,
    time_off text,
    duration_hours numeric(9,3),
    work_type_code varchar(10),
    altered_flag boolean,
    ro_number varchar(20) NOT NULL,
    payroll_export_batch_id varchar(20),
    indirect_time_code varchar(10),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (technician_id, line_code, work_date, time_on, ro_number)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_technician_time_punch.technician_id IS '[D] Technician ID';
COMMENT ON COLUMN cdk_technician_time_punch.line_code IS '[D] Repair Line Code';
COMMENT ON COLUMN cdk_technician_time_punch.work_date IS '[D] Work Date';
COMMENT ON COLUMN cdk_technician_time_punch.time_on IS '[D] Time Punched On';
COMMENT ON COLUMN cdk_technician_time_punch.time_off IS '[D] Time Punched Off';
COMMENT ON COLUMN cdk_technician_time_punch.duration_hours IS '[D] Duration Hours';
COMMENT ON COLUMN cdk_technician_time_punch.work_type_code IS '[D] Work Type Code';
COMMENT ON COLUMN cdk_technician_time_punch.altered_flag IS '[D] Altered Flag';
COMMENT ON COLUMN cdk_technician_time_punch.ro_number IS '[D] Associated RO Number';
COMMENT ON COLUMN cdk_technician_time_punch.payroll_export_batch_id IS '[U] Payroll Export Batch ID';
COMMENT ON COLUMN cdk_technician_time_punch.indirect_time_code IS '[U] Indirect/Non-RO Time Code';
COMMENT ON COLUMN cdk_technician_time_punch._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_technician_time_punch._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_technician_time_punch._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_technician_time_punch._batch_id IS '[D] the extract run/batch identifier this row landed with';
