-- cdk_technician_time_punch (technician-time-punch) -- Technician Time Punch
-- one clock in/out event against an RO labour line
-- SAP analogue: Time confirmation (CATS-style) feeding activity allocation
-- grain: one row per punch event
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_technician_time_punch (
    punch_id varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (punch_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_technician_time_punch.punch_id IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_technician_time_punch.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_technician_time_punch.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_technician_time_punch.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_technician_time_punch._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_technician_time_punch._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_technician_time_punch._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_technician_time_punch._batch_id IS '[D] the extract run/batch identifier this row landed with';
