-- cdk_vehicle_master (vehicle-master) -- Vehicle / Unit Master
-- the truck or unit record, keyed by VIN
-- SAP analogue: Equipment master (EQUI), serialized — VIN as equipment number
-- grain: one row per VIN
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_vehicle_master (
    vin varchar(12) NOT NULL,
    amount numeric(13,2),
    created_date date,
    status_code varchar(2),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (vin)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_vehicle_master.vin IS '[D] the key you''d look this record up by';
COMMENT ON COLUMN cdk_vehicle_master.amount IS '[D] the dollar amount on this line';
COMMENT ON COLUMN cdk_vehicle_master.created_date IS '[I] when this record was first created';
COMMENT ON COLUMN cdk_vehicle_master.status_code IS '[U] the status shown on the screen (values: O=Open; C=Closed)';
COMMENT ON COLUMN cdk_vehicle_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_vehicle_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_vehicle_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_vehicle_master._batch_id IS '[D] the extract run/batch identifier this row landed with';
