-- cdk_vehicle_master (vehicle-master) -- Vehicle Master
-- Vehicle
-- SAP analogue: EQUI (Equipment Master) — closest SAP analogue for a serialized asset record
-- grain: one row per vehicle (VIN) per rooftop
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_vehicle_master (
    vehicle_id varchar(32) NOT NULL,
    vin varchar(17) NOT NULL,
    license_plate_number varchar(15),
    make_code varchar(10),
    make varchar(40),
    model_code varchar(10),
    model varchar(40),
    model_year bigint,
    exterior_color varchar(30),
    mileage_value numeric(13,3),
    mileage_units varchar(32),
    vehicle_status varchar(32),
    date_delivered date,
    date_in_service date,
    warranty_expiration_date date,
    owner_href varchar(255),
    primary_driver_href varchar(255),
    stock_number varchar(15),
    lot_location varchar(20),
    ro_embedded_veh_id varchar(32),
    ro_embedded_delivery_date date,
    ro_embedded_vehicle_color varchar(30),
    ro_embedded_make_desc varchar(40),
    ro_embedded_model_desc varchar(40),
    is_sold_by_dealer boolean,
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (vehicle_id)
);

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_vehicle_master.vehicle_id IS '[D] Vehicle ID';
COMMENT ON COLUMN cdk_vehicle_master.vin IS '[D] VIN';
COMMENT ON COLUMN cdk_vehicle_master.license_plate_number IS '[D] License Plate Number';
COMMENT ON COLUMN cdk_vehicle_master.make_code IS '[D] Make Code';
COMMENT ON COLUMN cdk_vehicle_master.make IS '[D] Make';
COMMENT ON COLUMN cdk_vehicle_master.model_code IS '[D] Model Code';
COMMENT ON COLUMN cdk_vehicle_master.model IS '[D] Model';
COMMENT ON COLUMN cdk_vehicle_master.model_year IS '[D] Model Year';
COMMENT ON COLUMN cdk_vehicle_master.exterior_color IS '[D] Exterior Color';
COMMENT ON COLUMN cdk_vehicle_master.mileage_value IS '[D] Mileage Value';
COMMENT ON COLUMN cdk_vehicle_master.mileage_units IS '[D] Mileage Units (values: MILES=Miles; KM=Kilometers)';
COMMENT ON COLUMN cdk_vehicle_master.vehicle_status IS '[D] Vehicle Status (values: new=New vehicle; used=Used vehicle; certified=Certified pre-owned)';
COMMENT ON COLUMN cdk_vehicle_master.date_delivered IS '[D] Date Delivered';
COMMENT ON COLUMN cdk_vehicle_master.date_in_service IS '[D] Date In Service';
COMMENT ON COLUMN cdk_vehicle_master.warranty_expiration_date IS '[D] Warranty Expiration Date';
COMMENT ON COLUMN cdk_vehicle_master.owner_href IS '[D] Owner Link (HATEOAS)';
COMMENT ON COLUMN cdk_vehicle_master.primary_driver_href IS '[D] Primary Driver Link (HATEOAS)';
COMMENT ON COLUMN cdk_vehicle_master.stock_number IS '[U] Stock Number';
COMMENT ON COLUMN cdk_vehicle_master.lot_location IS '[D] Lot Location';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_veh_id IS '[D] RO-Embedded Vehicle ID';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_delivery_date IS '[D] RO-Embedded Delivery Date';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_vehicle_color IS '[D] RO-Embedded Vehicle Color';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_make_desc IS '[D] RO-Embedded Make Description';
COMMENT ON COLUMN cdk_vehicle_master.ro_embedded_model_desc IS '[D] RO-Embedded Model Description';
COMMENT ON COLUMN cdk_vehicle_master.is_sold_by_dealer IS '[D] Sold By This Dealer Flag';
COMMENT ON COLUMN cdk_vehicle_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_vehicle_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_vehicle_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_vehicle_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_vehicle_master ADD CONSTRAINT fk_cdk_vehicle_master_owner_href FOREIGN KEY (owner_href) REFERENCES cdk_customer_master (customer_id);
ALTER TABLE cdk_vehicle_master ADD CONSTRAINT fk_cdk_vehicle_master_primary_driver_href FOREIGN KEY (primary_driver_href) REFERENCES cdk_customer_master (customer_id);
ALTER TABLE cdk_vehicle_master ADD CONSTRAINT fk_cdk_vehicle_master_ro_embedded_veh_id FOREIGN KEY (ro_embedded_veh_id) REFERENCES cdk_vehicle_master (vehicle_id);
