-- cdk_vendor_master (vendor-master) -- Vendor Master
-- Vendor
-- SAP analogue: LFA1 (General Vendor Master) / LFB1 (Company Code Data)
-- grain: one row per vendor per rooftop
-- api reach: none
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_vendor_master (
    vendor_id varchar(20),
    vendor_name varchar(80),
    remit_to_address_line1 varchar(60),
    remit_to_city varchar(40),
    remit_to_state varchar(10),
    remit_to_postal_code varchar(15),
    tax_id_1099 varchar(20),
    gst_hst_number varchar(20),
    vendor_class varchar(32),
    payment_terms varchar(20),
    ap_control_gl_account varchar(10),
    vendor_status varchar(32),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (vendor_id)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on vendor_id: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_vendor_master.vendor_id IS '[I] Vendor ID [WIDENED per WIDENING-POLICY.md: SAP LFA1-LIFNR is CHAR(10); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_vendor_master.vendor_name IS '[I] Vendor Name [WIDENED per WIDENING-POLICY.md: SAP LFA1-NAME1 is CHAR(35); DDL emits source-native 80]';
COMMENT ON COLUMN cdk_vendor_master.remit_to_address_line1 IS '[I] Remit-To Address Line 1 [WIDENED per WIDENING-POLICY.md: SAP LFA1-STRAS is CHAR(35); DDL emits source-native 60]';
COMMENT ON COLUMN cdk_vendor_master.remit_to_city IS '[I] Remit-To City [WIDENED per WIDENING-POLICY.md: SAP LFA1-ORT01 is CHAR(35); DDL emits source-native 40]';
COMMENT ON COLUMN cdk_vendor_master.remit_to_state IS '[I] Remit-To State [WIDENED per WIDENING-POLICY.md: SAP LFA1-REGIO is CHAR(3); DDL emits source-native 10]';
COMMENT ON COLUMN cdk_vendor_master.remit_to_postal_code IS '[I] Remit-To Postal Code [WIDENED per WIDENING-POLICY.md: SAP LFA1-PSTLZ is CHAR(10); DDL emits source-native 15]';
COMMENT ON COLUMN cdk_vendor_master.tax_id_1099 IS '[I] 1099 Tax ID [WIDENED per WIDENING-POLICY.md: SAP LFA1-STCD1 is CHAR(16); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_vendor_master.gst_hst_number IS '[I] GST/HST Number [WIDENED per WIDENING-POLICY.md: SAP LFA1-STCD3 is CHAR(18); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_vendor_master.vendor_class IS '[U] Vendor Classification (values: OEM=OEM/factory vendor (e.g. PACCAR); SUBLET=Sublet repair vendor; TRADE=Local trade vendor; OTHER=Other/general vendor)';
COMMENT ON COLUMN cdk_vendor_master.payment_terms IS '[I] Payment Terms [WIDENED per WIDENING-POLICY.md: SAP LFB1-ZTERM is CHAR(4); DDL emits source-native 20]';
COMMENT ON COLUMN cdk_vendor_master.ap_control_gl_account IS '[I] AP Control GL Account';
COMMENT ON COLUMN cdk_vendor_master.vendor_status IS '[U] Vendor Status (values: ACTIVE=Active vendor; HOLD=Payment hold; INACTIVE=Inactive/closed)';
COMMENT ON COLUMN cdk_vendor_master._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_vendor_master._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_vendor_master._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_vendor_master._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_vendor_master ADD CONSTRAINT fk_cdk_vendor_master_ap_control_gl_account FOREIGN KEY (ap_control_gl_account) REFERENCES cdk_gl_account_master (gl_account_number);
