-- cdk_work_in_process (work-in-process) -- Work In Process
-- WIP Schedule
-- SAP analogue: Anlagen im Bau (AIB) suspense-account analogue / CO-PA WIP settlement (conceptual analogue only)
-- grain: one row per RO per WIP snapshot date
-- api reach: partial
-- generated by schema/bin/gen_ddl.py from contract EgD-CDK-FIELDS-v2 -- do not hand-edit, regenerate instead

CREATE TABLE IF NOT EXISTS cdk_work_in_process (
    wip_snapshot_date date,
    ro_number varchar(20) NOT NULL,
    wip_status varchar(32) NOT NULL,
    wip_labor_amount numeric(13,2),
    wip_parts_amount numeric(13,2),
    wip_opened_date date,
    wip_age_days numeric(13,3),
    wip_closed_date date,
    wip_gl_account varchar(10),
    wip_department_suffix varchar(4),
    _rooftop_id varchar(20),
    _extracted_at timestamptz,
    _source_route varchar(16),
    _batch_id varchar(64),
    PRIMARY KEY (wip_snapshot_date, ro_number)
);

-- Inferred/unverified NOT NULL constraints withheld (documented in fields.json but not enforced here):
    -- NOT NULL withheld on wip_snapshot_date: nullable=false per source but confidence=INFERRED (never enforce a constraint on an inference)

-- Column comments (dealer-language label + confidence mark: [D]=documented [I]=inferred [U]=unverified)
COMMENT ON COLUMN cdk_work_in_process.wip_snapshot_date IS '[I] the date this work-in-process balance was captured';
COMMENT ON COLUMN cdk_work_in_process.ro_number IS '[D] Associated RO Number';
COMMENT ON COLUMN cdk_work_in_process.wip_status IS '[D] WIP Status (values: OPENED=RO opened within the WIP window (past 48h); VOIDED=RO voided within the WIP window; CLOSED=RO closed within the WIP window)';
COMMENT ON COLUMN cdk_work_in_process.wip_labor_amount IS '[I] WIP Labor Amount (suspense)';
COMMENT ON COLUMN cdk_work_in_process.wip_parts_amount IS '[I] WIP Parts Amount (suspense)';
COMMENT ON COLUMN cdk_work_in_process.wip_opened_date IS '[D] WIP Opened Date';
COMMENT ON COLUMN cdk_work_in_process.wip_age_days IS '[I] WIP Age in Days';
COMMENT ON COLUMN cdk_work_in_process.wip_closed_date IS '[D] WIP Closed Date';
COMMENT ON COLUMN cdk_work_in_process.wip_gl_account IS '[I] WIP GL Suspense Account';
COMMENT ON COLUMN cdk_work_in_process.wip_department_suffix IS '[I] WIP Department/Cost-Centre Suffix';
COMMENT ON COLUMN cdk_work_in_process._rooftop_id IS '[D] which rooftop/store this extracted row belongs to';
COMMENT ON COLUMN cdk_work_in_process._extracted_at IS '[D] when this row was pulled from CDK by the extract harness';
COMMENT ON COLUMN cdk_work_in_process._source_route IS '[D] which of the three extract routes produced this row: fortellis | export | screen';
COMMENT ON COLUMN cdk_work_in_process._batch_id IS '[D] the extract run/batch identifier this row landed with';

-- Foreign keys
ALTER TABLE cdk_work_in_process ADD CONSTRAINT fk_cdk_work_in_process_wip_gl_account FOREIGN KEY (wip_gl_account) REFERENCES cdk_gl_account_master (gl_account_number);
ALTER TABLE cdk_work_in_process ADD CONSTRAINT fk_cdk_work_in_process_wip_department_suffix FOREIGN KEY (wip_department_suffix) REFERENCES cdk_cost_centre_department (department_code);
