-- schema/ddl/enums/000_enum_tables.sql
--
-- Reference-table DDL for the CDK Twin code lists (pay type, RO status, labour-op
-- type, parts source/price class, GL account type, document type, schedule control
-- key). Hand-authored, not generated by schema/bin/gen_ddl.py, because fields.json
-- (contract EgD-CDK-FIELDS-v2) carries per-field enum_values inline on the field that
-- uses a code, not a standalone code-list catalogue -- these tables ARE that catalogue,
-- built once here so the extract has somewhere to validate against and so tomorrow's
-- discovery has somewhere to land instead of a blank slate.
--
-- Every seed row carries a `confidence` column (DOCUMENTED | INFERRED | UNVERIFIED)
-- and a `source_url` column. Postgres dialect; portable to Snowflake with no dialect-
-- specific syntax (VARCHAR/NUMERIC only, no serial/identity columns).
--
-- Run after schema/ddl/postgres/000_all.sql (these tables are referenced by
-- fk_target-style lookups from the entity tables' *_code columns, though those FKs
-- are not enforced here -- see schema/README.md for why code-list FKs stay soft).

-- ---------------------------------------------------------------------------
-- Shared shape used by every code-list table in this file.
-- code            the literal code as it appears on the CDK screen/payload
-- meaning         plain-language meaning
-- confidence      DOCUMENTED | INFERRED | UNVERIFIED -- per row, never uniform
-- source_url      where this row's meaning was confirmed, or NULL for UNVERIFIED stubs
-- notes           short, only when it earns its place
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cdk_codelist_pay_type (
    code varchar(4) NOT NULL,
    meaning varchar(128) NOT NULL,
    confidence varchar(11) NOT NULL,
    source_url varchar(512),
    notes varchar(256),
    PRIMARY KEY (code)
);
COMMENT ON TABLE cdk_codelist_pay_type IS 'RO payer settlement rule -- which of three receivable schedules an RO settles to (customer / warranty / internal), per FIELD_CONTRACT.md sap_analogue: internal order (AUFK/COEP) settlement rule.';

INSERT INTO cdk_codelist_pay_type (code, meaning, confidence, source_url, notes) VALUES
    ('C', 'Customer pay', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'Settles to the customer accounting-schedule/receivable.'),
    ('W', 'Warranty pay', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'Settles to the factory/PACCAR warranty receivable schedule.'),
    ('I', 'Internal pay', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'Settles internally -- shop supplies, PDI, or dealer-absorbed cost.'),
    ('U', 'Unconfirmed code', 'UNVERIFIED', NULL, 'Stub row -- confirm remaining pay-type codes (e.g. split/mixed-pay ROs) on tenant login.');

-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cdk_codelist_ro_status (
    code varchar(4) NOT NULL,
    meaning varchar(128) NOT NULL,
    confidence varchar(11) NOT NULL,
    source_url varchar(512),
    notes varchar(256),
    PRIMARY KEY (code)
);
COMMENT ON TABLE cdk_codelist_ro_status IS 'Repair order lifecycle status -- also the accounting-side WIP/closed distinction (work-in-process entity).';

INSERT INTO cdk_codelist_ro_status (code, meaning, confidence, source_url, notes) VALUES
    ('OPEN', 'Open / work in process', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'Carried as WIP on the balance sheet while open.'),
    ('CLOSED', 'Closed / invoiced', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'RO has settled and left WIP.'),
    ('VOID', 'Voided', 'INFERRED', NULL, 'Reasoned from standard DMS RO lifecycle convention; not confirmed field-level in Fortellis docs.'),
    ('UNVERIFIED_STUB', 'Unconfirmed status code', 'UNVERIFIED', NULL, 'Stub row -- CDK likely has intermediate statuses (e.g. dispatched, in-progress by department); confirm on tenant login.');

-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cdk_codelist_labour_op_type (
    code varchar(4) NOT NULL,
    meaning varchar(128) NOT NULL,
    confidence varchar(11) NOT NULL,
    source_url varchar(512),
    notes varchar(256),
    PRIMARY KEY (code)
);
COMMENT ON TABLE cdk_codelist_labour_op_type IS 'RO labour-operation type -- distinguishes billed repair labour from sublet, goodwill, and shop-supply lines.';

INSERT INTO cdk_codelist_labour_op_type (code, meaning, confidence, source_url, notes) VALUES
    ('RO', 'Standard repair operation', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'laborOperations[] line billed at the standard flat-rate/actual-hours rule.'),
    ('SUB', 'Sublet operation', 'INFERRED', NULL, 'Reasoned from standard dealer-accounting practice; CDK field-level sublet flag not directly documented at this depth.'),
    ('GW', 'Goodwill / policy adjustment', 'INFERRED', NULL, 'Reasoned from standard dealer-accounting practice for policy/goodwill labour write-offs.'),
    ('UNVERIFIED_STUB', 'Unconfirmed labour-op type', 'UNVERIFIED', NULL, 'Stub row -- confirm the full labour-op-type code list on tenant login.');

-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cdk_codelist_parts_source (
    code varchar(4) NOT NULL,
    meaning varchar(128) NOT NULL,
    confidence varchar(11) NOT NULL,
    source_url varchar(512),
    notes varchar(256),
    PRIMARY KEY (code)
);
COMMENT ON TABLE cdk_codelist_parts_source IS 'Parts source code -- where a part line was fulfilled from (stock, special order, PACCAR OPC/MDI, etc).';

INSERT INTO cdk_codelist_parts_source (code, meaning, confidence, source_url, notes) VALUES
    ('STK', 'Stock', 'INFERRED', NULL, 'Reasoned from standard parts-inventory convention; not directly documented at field level.'),
    ('IRO', 'Immediate Requirement Order', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'Named order type confirmed in parts-order-supersession research (Module 04).'),
    ('IRE', 'Immediate Requirement Expedite', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'Named order type confirmed alongside IRO.'),
    ('RMR', 'Return Merchandise Request', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'Named order type confirmed in the parts ordering workflow.'),
    ('UNVERIFIED_STUB', 'Unconfirmed parts-source code', 'UNVERIFIED', NULL, 'Stub row -- confirm full parts-source/price-class code list on tenant login.');

-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cdk_codelist_parts_price_class (
    code varchar(4) NOT NULL,
    meaning varchar(128) NOT NULL,
    confidence varchar(11) NOT NULL,
    source_url varchar(512),
    notes varchar(256),
    PRIMARY KEY (code)
);
COMMENT ON TABLE cdk_codelist_parts_price_class IS 'Parts price/customer class -- affects the pricing matrix applied at the counter (customer-master.partsType feeds this).';

INSERT INTO cdk_codelist_parts_price_class (code, meaning, confidence, source_url, notes) VALUES
    ('W', 'Wholesale', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'partsType=W on the customer master marks a wholesale parts customer.'),
    ('R', 'Retail', 'INFERRED', NULL, 'Reasoned as the counterpart to wholesale; not independently documented at field level.'),
    ('UNVERIFIED_STUB', 'Unconfirmed price-class code', 'UNVERIFIED', NULL, 'Stub row -- confirm full price-class code list on tenant login.');

-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cdk_codelist_gl_account_type (
    code varchar(4) NOT NULL,
    meaning varchar(128) NOT NULL,
    confidence varchar(11) NOT NULL,
    source_url varchar(512),
    notes varchar(256),
    PRIMARY KEY (code)
);
COMMENT ON TABLE cdk_codelist_gl_account_type IS 'GL account type -- balance sheet vs income statement vs control/reconciliation account, per gl-account-master (SAP analogue SKA1/SKB1).';

INSERT INTO cdk_codelist_gl_account_type (code, meaning, confidence, source_url, notes) VALUES
    ('BS', 'Balance sheet account', 'INFERRED', NULL, 'Reasoned from standard chart-of-accounts convention; CDK GL account master has no public field-level schema (api_reach: none).'),
    ('IS', 'Income statement account', 'INFERRED', NULL, 'Reasoned from standard chart-of-accounts convention; same api_reach: none caveat.'),
    ('CTRL', 'Control / reconciliation account', 'INFERRED', NULL, 'Reasoned as the account type an accounting-schedule subledger sits behind.'),
    ('UNVERIFIED_STUB', 'Unconfirmed GL account type', 'UNVERIFIED', NULL, 'Stub row -- GL account master is api_reach:none; full type code list must come from the DMS UI export on tenant login.');

-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cdk_codelist_document_type (
    code varchar(4) NOT NULL,
    meaning varchar(128) NOT NULL,
    confidence varchar(11) NOT NULL,
    source_url varchar(512),
    notes varchar(256),
    PRIMARY KEY (code)
);
COMMENT ON TABLE cdk_codelist_document_type IS 'Document type -- classifies gl-journal-posting and purchase-receipt-document rows (SAP analogue BKPF-BLART).';

INSERT INTO cdk_codelist_document_type (code, meaning, confidence, source_url, notes) VALUES
    ('JE', 'Journal entry', 'INFERRED', NULL, 'Reasoned from standard GL posting convention; gl-journal-posting api_reach is partial with UNVERIFIED request/response schema.'),
    ('PO', 'Purchase order', 'INFERRED', NULL, 'Reasoned from standard 3-way-match convention.'),
    ('GR', 'Goods receipt', 'INFERRED', NULL, 'Reasoned from standard 3-way-match convention against purchase-receipt-document.'),
    ('AP', 'AP invoice', 'INFERRED', NULL, 'Reasoned from standard 3-way-match convention.'),
    ('UNVERIFIED_STUB', 'Unconfirmed document type', 'UNVERIFIED', NULL, 'Stub row -- confirm full document-type code list on tenant login (purchase-receipt-document is api_reach:none).');

-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cdk_codelist_schedule_control_key (
    code varchar(8) NOT NULL,
    meaning varchar(128) NOT NULL,
    confidence varchar(11) NOT NULL,
    source_url varchar(512),
    notes varchar(256),
    PRIMARY KEY (code)
);
COMMENT ON TABLE cdk_codelist_schedule_control_key IS 'Accounting-schedule control-key type -- what an open item in a schedule is keyed by (RO number, stock number, VIN last 8).';

INSERT INTO cdk_codelist_schedule_control_key (code, meaning, confidence, source_url, notes) VALUES
    ('RO_NO', 'RO number', 'DOCUMENTED', 'https://fortellis-api-documents-prod.s3-us-west-2.amazonaws.com/f83a79c6-8cf9-4c1a-b45e-b266634eaf90/external/20251119155158640--ZuFlj8i.pdf', 'Confirmed in Module 02/03 research: repair-order-keyed schedules exist.'),
    ('STOCK_NO', 'Stock number', 'INFERRED', NULL, 'Reasoned from standard dealer-accounting practice for vehicle-inventory schedules.'),
    ('VIN8', 'VIN last 8', 'INFERRED', NULL, 'Reasoned from standard dealer-accounting practice for in-transit/floorplan schedules.'),
    ('UNVERIFIED_STUB', 'Unconfirmed control-key type', 'UNVERIFIED', NULL, 'Stub row -- accounting-schedule is api_reach:none; confirm full control-key type list on tenant login / DMS UI export.');

-- ---------------------------------------------------------------------------
-- End of code-list seed DDL. Every table above ends in an UNVERIFIED_STUB row
-- so tomorrow's discovery (CDK admin login) has a concrete place to insert
-- newly-confirmed codes rather than starting from a blank table.
